/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ActivityPlanResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class ActivityPlanResponse   {
  @SerializedName("activityDetail")
  private String activityDetail = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("learningOutcome")
  private String learningOutcome = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("resourceRequired")
  private String resourceRequired = null;

  @SerializedName("skillsConcept")
  private String skillsConcept = null;

  @SerializedName("suggestedDuration")
  private String suggestedDuration = null;

  @SerializedName("type")
  private Integer type = null;

  public ActivityPlanResponse activityDetail(String activityDetail) {
    this.activityDetail = activityDetail;
    return this;
  }

   /**
   * Get activityDetail
   * @return activityDetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getActivityDetail() {
    return activityDetail;
  }

  public void setActivityDetail(String activityDetail) {
    this.activityDetail = activityDetail;
  }

  public ActivityPlanResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ActivityPlanResponse learningOutcome(String learningOutcome) {
    this.learningOutcome = learningOutcome;
    return this;
  }

   /**
   * Get learningOutcome
   * @return learningOutcome
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLearningOutcome() {
    return learningOutcome;
  }

  public void setLearningOutcome(String learningOutcome) {
    this.learningOutcome = learningOutcome;
  }

  public ActivityPlanResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActivityPlanResponse resourceRequired(String resourceRequired) {
    this.resourceRequired = resourceRequired;
    return this;
  }

   /**
   * Get resourceRequired
   * @return resourceRequired
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResourceRequired() {
    return resourceRequired;
  }

  public void setResourceRequired(String resourceRequired) {
    this.resourceRequired = resourceRequired;
  }

  public ActivityPlanResponse skillsConcept(String skillsConcept) {
    this.skillsConcept = skillsConcept;
    return this;
  }

   /**
   * Get skillsConcept
   * @return skillsConcept
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSkillsConcept() {
    return skillsConcept;
  }

  public void setSkillsConcept(String skillsConcept) {
    this.skillsConcept = skillsConcept;
  }

  public ActivityPlanResponse suggestedDuration(String suggestedDuration) {
    this.suggestedDuration = suggestedDuration;
    return this;
  }

   /**
   * Get suggestedDuration
   * @return suggestedDuration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSuggestedDuration() {
    return suggestedDuration;
  }

  public void setSuggestedDuration(String suggestedDuration) {
    this.suggestedDuration = suggestedDuration;
  }

  public ActivityPlanResponse type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityPlanResponse activityPlanResponse = (ActivityPlanResponse) o;
    return Objects.equals(this.activityDetail, activityPlanResponse.activityDetail) &&
        Objects.equals(this.id, activityPlanResponse.id) &&
        Objects.equals(this.learningOutcome, activityPlanResponse.learningOutcome) &&
        Objects.equals(this.name, activityPlanResponse.name) &&
        Objects.equals(this.resourceRequired, activityPlanResponse.resourceRequired) &&
        Objects.equals(this.skillsConcept, activityPlanResponse.skillsConcept) &&
        Objects.equals(this.suggestedDuration, activityPlanResponse.suggestedDuration) &&
        Objects.equals(this.type, activityPlanResponse.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activityDetail, id, learningOutcome, name, resourceRequired, skillsConcept, suggestedDuration, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityPlanResponse {\n");
    
    sb.append("    activityDetail: ").append(toIndentedString(activityDetail)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    learningOutcome: ").append(toIndentedString(learningOutcome)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    resourceRequired: ").append(toIndentedString(resourceRequired)).append("\n");
    sb.append("    skillsConcept: ").append(toIndentedString(skillsConcept)).append("\n");
    sb.append("    suggestedDuration: ").append(toIndentedString(suggestedDuration)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

