/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.AssessmentResponse;
import com.nexteducation.swagger.nextsws.model.AssessmentTemplateMasterResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AssessmentTemplateConfigurationResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class AssessmentTemplateConfigurationResponse   {
  @SerializedName("assessment")
  private AssessmentResponse assessment = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("master")
  private AssessmentTemplateMasterResponse master = null;

  @SerializedName("value")
  private String value = null;

  public AssessmentTemplateConfigurationResponse assessment(AssessmentResponse assessment) {
    this.assessment = assessment;
    return this;
  }

   /**
   * Get assessment
   * @return assessment
  **/
  @ApiModelProperty(example = "null", value = "")
  public AssessmentResponse getAssessment() {
    return assessment;
  }

  public void setAssessment(AssessmentResponse assessment) {
    this.assessment = assessment;
  }

  public AssessmentTemplateConfigurationResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AssessmentTemplateConfigurationResponse master(AssessmentTemplateMasterResponse master) {
    this.master = master;
    return this;
  }

   /**
   * Get master
   * @return master
  **/
  @ApiModelProperty(example = "null", value = "")
  public AssessmentTemplateMasterResponse getMaster() {
    return master;
  }

  public void setMaster(AssessmentTemplateMasterResponse master) {
    this.master = master;
  }

  public AssessmentTemplateConfigurationResponse value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssessmentTemplateConfigurationResponse assessmentTemplateConfigurationResponse = (AssessmentTemplateConfigurationResponse) o;
    return Objects.equals(this.assessment, assessmentTemplateConfigurationResponse.assessment) &&
        Objects.equals(this.id, assessmentTemplateConfigurationResponse.id) &&
        Objects.equals(this.master, assessmentTemplateConfigurationResponse.master) &&
        Objects.equals(this.value, assessmentTemplateConfigurationResponse.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assessment, id, master, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssessmentTemplateConfigurationResponse {\n");
    
    sb.append("    assessment: ").append(toIndentedString(assessment)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    master: ").append(toIndentedString(master)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

