/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.ConceptResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * ConceptEdgeResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class ConceptEdgeResponse   {
  @SerializedName("branchID")
  private Long branchID = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("createdOn")
  private DateTime createdOn = null;

  @SerializedName("fromConcept")
  private ConceptResponse fromConcept = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("modifiedOn")
  private DateTime modifiedOn = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("relationID")
  private Long relationID = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("InActive")
    INACTIVE("InActive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  /**
   * Gets or Sets style
   */
  public enum StyleEnum {
    @SerializedName("dashed")
    DASHED("dashed"),
    
    @SerializedName("solid")
    SOLID("solid");

    private String value;

    StyleEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("style")
  private StyleEnum style = null;

  @SerializedName("toConcept")
  private ConceptResponse toConcept = null;

  @SerializedName("uniqueID")
  private String uniqueID = null;

  @SerializedName("weight")
  private Float weight = null;

  public ConceptEdgeResponse branchID(Long branchID) {
    this.branchID = branchID;
    return this;
  }

   /**
   * Get branchID
   * @return branchID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchID() {
    return branchID;
  }

  public void setBranchID(Long branchID) {
    this.branchID = branchID;
  }

  public ConceptEdgeResponse color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public ConceptEdgeResponse createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public ConceptEdgeResponse createdOn(DateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(DateTime createdOn) {
    this.createdOn = createdOn;
  }

  public ConceptEdgeResponse fromConcept(ConceptResponse fromConcept) {
    this.fromConcept = fromConcept;
    return this;
  }

   /**
   * Get fromConcept
   * @return fromConcept
  **/
  @ApiModelProperty(example = "null", value = "")
  public ConceptResponse getFromConcept() {
    return fromConcept;
  }

  public void setFromConcept(ConceptResponse fromConcept) {
    this.fromConcept = fromConcept;
  }

  public ConceptEdgeResponse label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ConceptEdgeResponse modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public ConceptEdgeResponse modifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * Get modifiedOn
   * @return modifiedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }

  public ConceptEdgeResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ConceptEdgeResponse relationID(Long relationID) {
    this.relationID = relationID;
    return this;
  }

   /**
   * Get relationID
   * @return relationID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getRelationID() {
    return relationID;
  }

  public void setRelationID(Long relationID) {
    this.relationID = relationID;
  }

  public ConceptEdgeResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ConceptEdgeResponse style(StyleEnum style) {
    this.style = style;
    return this;
  }

   /**
   * Get style
   * @return style
  **/
  @ApiModelProperty(example = "null", value = "")
  public StyleEnum getStyle() {
    return style;
  }

  public void setStyle(StyleEnum style) {
    this.style = style;
  }

  public ConceptEdgeResponse toConcept(ConceptResponse toConcept) {
    this.toConcept = toConcept;
    return this;
  }

   /**
   * Get toConcept
   * @return toConcept
  **/
  @ApiModelProperty(example = "null", value = "")
  public ConceptResponse getToConcept() {
    return toConcept;
  }

  public void setToConcept(ConceptResponse toConcept) {
    this.toConcept = toConcept;
  }

  public ConceptEdgeResponse uniqueID(String uniqueID) {
    this.uniqueID = uniqueID;
    return this;
  }

   /**
   * Get uniqueID
   * @return uniqueID
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUniqueID() {
    return uniqueID;
  }

  public void setUniqueID(String uniqueID) {
    this.uniqueID = uniqueID;
  }

  public ConceptEdgeResponse weight(Float weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getWeight() {
    return weight;
  }

  public void setWeight(Float weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConceptEdgeResponse conceptEdgeResponse = (ConceptEdgeResponse) o;
    return Objects.equals(this.branchID, conceptEdgeResponse.branchID) &&
        Objects.equals(this.color, conceptEdgeResponse.color) &&
        Objects.equals(this.createdBy, conceptEdgeResponse.createdBy) &&
        Objects.equals(this.createdOn, conceptEdgeResponse.createdOn) &&
        Objects.equals(this.fromConcept, conceptEdgeResponse.fromConcept) &&
        Objects.equals(this.label, conceptEdgeResponse.label) &&
        Objects.equals(this.modifiedBy, conceptEdgeResponse.modifiedBy) &&
        Objects.equals(this.modifiedOn, conceptEdgeResponse.modifiedOn) &&
        Objects.equals(this.name, conceptEdgeResponse.name) &&
        Objects.equals(this.relationID, conceptEdgeResponse.relationID) &&
        Objects.equals(this.status, conceptEdgeResponse.status) &&
        Objects.equals(this.style, conceptEdgeResponse.style) &&
        Objects.equals(this.toConcept, conceptEdgeResponse.toConcept) &&
        Objects.equals(this.uniqueID, conceptEdgeResponse.uniqueID) &&
        Objects.equals(this.weight, conceptEdgeResponse.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(branchID, color, createdBy, createdOn, fromConcept, label, modifiedBy, modifiedOn, name, relationID, status, style, toConcept, uniqueID, weight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConceptEdgeResponse {\n");
    
    sb.append("    branchID: ").append(toIndentedString(branchID)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    fromConcept: ").append(toIndentedString(fromConcept)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relationID: ").append(toIndentedString(relationID)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    toConcept: ").append(toIndentedString(toConcept)).append("\n");
    sb.append("    uniqueID: ").append(toIndentedString(uniqueID)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

