/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.LearningPlanTypeAndDurationResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * LearningPlanShortResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class LearningPlanShortResponse   {
  @SerializedName("date")
  private DateTime date = null;

  @SerializedName("learningPlanTypeAndDurationResponses")
  private List<LearningPlanTypeAndDurationResponse> learningPlanTypeAndDurationResponses = new ArrayList<LearningPlanTypeAndDurationResponse>();

  @SerializedName("type")
  private String type = null;

  public LearningPlanShortResponse date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public LearningPlanShortResponse learningPlanTypeAndDurationResponses(List<LearningPlanTypeAndDurationResponse> learningPlanTypeAndDurationResponses) {
    this.learningPlanTypeAndDurationResponses = learningPlanTypeAndDurationResponses;
    return this;
  }

  public LearningPlanShortResponse addLearningPlanTypeAndDurationResponsesItem(LearningPlanTypeAndDurationResponse learningPlanTypeAndDurationResponsesItem) {
    this.learningPlanTypeAndDurationResponses.add(learningPlanTypeAndDurationResponsesItem);
    return this;
  }

   /**
   * Get learningPlanTypeAndDurationResponses
   * @return learningPlanTypeAndDurationResponses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LearningPlanTypeAndDurationResponse> getLearningPlanTypeAndDurationResponses() {
    return learningPlanTypeAndDurationResponses;
  }

  public void setLearningPlanTypeAndDurationResponses(List<LearningPlanTypeAndDurationResponse> learningPlanTypeAndDurationResponses) {
    this.learningPlanTypeAndDurationResponses = learningPlanTypeAndDurationResponses;
  }

  public LearningPlanShortResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LearningPlanShortResponse learningPlanShortResponse = (LearningPlanShortResponse) o;
    return Objects.equals(this.date, learningPlanShortResponse.date) &&
        Objects.equals(this.learningPlanTypeAndDurationResponses, learningPlanShortResponse.learningPlanTypeAndDurationResponses) &&
        Objects.equals(this.type, learningPlanShortResponse.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, learningPlanTypeAndDurationResponses, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LearningPlanShortResponse {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    learningPlanTypeAndDurationResponses: ").append(toIndentedString(learningPlanTypeAndDurationResponses)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

