/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * LearningPlanTypeAndDurationResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class LearningPlanTypeAndDurationResponse   {
  @SerializedName("duration")
  private String duration = null;

  @SerializedName("learningPlanType")
  private String learningPlanType = null;

  @SerializedName("learningPlanUuid")
  private String learningPlanUuid = null;

  public LearningPlanTypeAndDurationResponse duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public LearningPlanTypeAndDurationResponse learningPlanType(String learningPlanType) {
    this.learningPlanType = learningPlanType;
    return this;
  }

   /**
   * Get learningPlanType
   * @return learningPlanType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLearningPlanType() {
    return learningPlanType;
  }

  public void setLearningPlanType(String learningPlanType) {
    this.learningPlanType = learningPlanType;
  }

  public LearningPlanTypeAndDurationResponse learningPlanUuid(String learningPlanUuid) {
    this.learningPlanUuid = learningPlanUuid;
    return this;
  }

   /**
   * Get learningPlanUuid
   * @return learningPlanUuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLearningPlanUuid() {
    return learningPlanUuid;
  }

  public void setLearningPlanUuid(String learningPlanUuid) {
    this.learningPlanUuid = learningPlanUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LearningPlanTypeAndDurationResponse learningPlanTypeAndDurationResponse = (LearningPlanTypeAndDurationResponse) o;
    return Objects.equals(this.duration, learningPlanTypeAndDurationResponse.duration) &&
        Objects.equals(this.learningPlanType, learningPlanTypeAndDurationResponse.learningPlanType) &&
        Objects.equals(this.learningPlanUuid, learningPlanTypeAndDurationResponse.learningPlanUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, learningPlanType, learningPlanUuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LearningPlanTypeAndDurationResponse {\n");
    
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    learningPlanType: ").append(toIndentedString(learningPlanType)).append("\n");
    sb.append("    learningPlanUuid: ").append(toIndentedString(learningPlanUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

