/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.LearningPlanTaskResponse;
import com.nexteducation.swagger.nextsws.model.ResourceResponse;
import com.nexteducation.swagger.nextsws.model.ResourceShortResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * LearningPlanTaskDetailResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class LearningPlanTaskDetailResponse   {
  @SerializedName("learningPlanResourceUuidToResourceResponseMap")
  private Map<String, ResourceResponse> learningPlanResourceUuidToResourceResponseMap = new HashMap<String, ResourceResponse>();

  @SerializedName("learningPlanResourceUuidToTasks")
  private Map<String, List<LearningPlanTaskResponse>> learningPlanResourceUuidToTasks = new HashMap<String, List<LearningPlanTaskResponse>>();

  @SerializedName("learningplanresources")
  private List<ResourceShortResponse> learningplanresources = new ArrayList<ResourceShortResponse>();

  @SerializedName("tasks")
  private LearningPlanTaskResponse tasks = null;

  public LearningPlanTaskDetailResponse learningPlanResourceUuidToResourceResponseMap(Map<String, ResourceResponse> learningPlanResourceUuidToResourceResponseMap) {
    this.learningPlanResourceUuidToResourceResponseMap = learningPlanResourceUuidToResourceResponseMap;
    return this;
  }

  public LearningPlanTaskDetailResponse putLearningPlanResourceUuidToResourceResponseMapItem(String key, ResourceResponse learningPlanResourceUuidToResourceResponseMapItem) {
    this.learningPlanResourceUuidToResourceResponseMap.put(key, learningPlanResourceUuidToResourceResponseMapItem);
    return this;
  }

   /**
   * Get learningPlanResourceUuidToResourceResponseMap
   * @return learningPlanResourceUuidToResourceResponseMap
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, ResourceResponse> getLearningPlanResourceUuidToResourceResponseMap() {
    return learningPlanResourceUuidToResourceResponseMap;
  }

  public void setLearningPlanResourceUuidToResourceResponseMap(Map<String, ResourceResponse> learningPlanResourceUuidToResourceResponseMap) {
    this.learningPlanResourceUuidToResourceResponseMap = learningPlanResourceUuidToResourceResponseMap;
  }

  public LearningPlanTaskDetailResponse learningPlanResourceUuidToTasks(Map<String, List<LearningPlanTaskResponse>> learningPlanResourceUuidToTasks) {
    this.learningPlanResourceUuidToTasks = learningPlanResourceUuidToTasks;
    return this;
  }

  public LearningPlanTaskDetailResponse putLearningPlanResourceUuidToTasksItem(String key, List<LearningPlanTaskResponse> learningPlanResourceUuidToTasksItem) {
    this.learningPlanResourceUuidToTasks.put(key, learningPlanResourceUuidToTasksItem);
    return this;
  }

   /**
   * Get learningPlanResourceUuidToTasks
   * @return learningPlanResourceUuidToTasks
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<LearningPlanTaskResponse>> getLearningPlanResourceUuidToTasks() {
    return learningPlanResourceUuidToTasks;
  }

  public void setLearningPlanResourceUuidToTasks(Map<String, List<LearningPlanTaskResponse>> learningPlanResourceUuidToTasks) {
    this.learningPlanResourceUuidToTasks = learningPlanResourceUuidToTasks;
  }

  public LearningPlanTaskDetailResponse learningplanresources(List<ResourceShortResponse> learningplanresources) {
    this.learningplanresources = learningplanresources;
    return this;
  }

  public LearningPlanTaskDetailResponse addLearningplanresourcesItem(ResourceShortResponse learningplanresourcesItem) {
    this.learningplanresources.add(learningplanresourcesItem);
    return this;
  }

   /**
   * Get learningplanresources
   * @return learningplanresources
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ResourceShortResponse> getLearningplanresources() {
    return learningplanresources;
  }

  public void setLearningplanresources(List<ResourceShortResponse> learningplanresources) {
    this.learningplanresources = learningplanresources;
  }

  public LearningPlanTaskDetailResponse tasks(LearningPlanTaskResponse tasks) {
    this.tasks = tasks;
    return this;
  }

   /**
   * Get tasks
   * @return tasks
  **/
  @ApiModelProperty(example = "null", value = "")
  public LearningPlanTaskResponse getTasks() {
    return tasks;
  }

  public void setTasks(LearningPlanTaskResponse tasks) {
    this.tasks = tasks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LearningPlanTaskDetailResponse learningPlanTaskDetailResponse = (LearningPlanTaskDetailResponse) o;
    return Objects.equals(this.learningPlanResourceUuidToResourceResponseMap, learningPlanTaskDetailResponse.learningPlanResourceUuidToResourceResponseMap) &&
        Objects.equals(this.learningPlanResourceUuidToTasks, learningPlanTaskDetailResponse.learningPlanResourceUuidToTasks) &&
        Objects.equals(this.learningplanresources, learningPlanTaskDetailResponse.learningplanresources) &&
        Objects.equals(this.tasks, learningPlanTaskDetailResponse.tasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(learningPlanResourceUuidToResourceResponseMap, learningPlanResourceUuidToTasks, learningplanresources, tasks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LearningPlanTaskDetailResponse {\n");
    
    sb.append("    learningPlanResourceUuidToResourceResponseMap: ").append(toIndentedString(learningPlanResourceUuidToResourceResponseMap)).append("\n");
    sb.append("    learningPlanResourceUuidToTasks: ").append(toIndentedString(learningPlanResourceUuidToTasks)).append("\n");
    sb.append("    learningplanresources: ").append(toIndentedString(learningplanresources)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

