/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * LectureBreakupRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class LectureBreakupRequest   {
  @SerializedName("academicSession")
  private Long academicSession = null;

  @SerializedName("branch")
  private Long branch = null;

  @SerializedName("chapterId")
  private Long chapterId = null;

  @SerializedName("classLectures")
  private Long classLectures = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("customChapter")
  private Boolean customChapter = null;

  @SerializedName("homeworkMin")
  private Long homeworkMin = null;

  @SerializedName("isCopyOf")
  private String isCopyOf = null;

  @SerializedName("labLectures")
  private Long labLectures = null;

  @SerializedName("lectureBreakUpUuids")
  private List<String> lectureBreakUpUuids = new ArrayList<String>();

  /**
   * Gets or Sets level
   */
  public enum LevelEnum {
    @SerializedName("Master")
    MASTER("Master"),
    
    @SerializedName("StudyClass")
    STUDYCLASS("StudyClass"),
    
    @SerializedName("Section")
    SECTION("Section");

    private String value;

    LevelEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("level")
  private LevelEnum level = null;

  @SerializedName("masterClass")
  private Long masterClass = null;

  @SerializedName("masterSubject")
  private Long masterSubject = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("section")
  private Long section = null;

  @SerializedName("seqNumber")
  private Long seqNumber = null;

  @SerializedName("shareable")
  private Boolean shareable = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("Inactive")
    INACTIVE("Inactive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("user")
  private Long user = null;

  @SerializedName("uuid")
  private String uuid = null;

  public LectureBreakupRequest academicSession(Long academicSession) {
    this.academicSession = academicSession;
    return this;
  }

   /**
   * Get academicSession
   * @return academicSession
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAcademicSession() {
    return academicSession;
  }

  public void setAcademicSession(Long academicSession) {
    this.academicSession = academicSession;
  }

  public LectureBreakupRequest branch(Long branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranch() {
    return branch;
  }

  public void setBranch(Long branch) {
    this.branch = branch;
  }

  public LectureBreakupRequest chapterId(Long chapterId) {
    this.chapterId = chapterId;
    return this;
  }

   /**
   * Get chapterId
   * @return chapterId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getChapterId() {
    return chapterId;
  }

  public void setChapterId(Long chapterId) {
    this.chapterId = chapterId;
  }

  public LectureBreakupRequest classLectures(Long classLectures) {
    this.classLectures = classLectures;
    return this;
  }

   /**
   * Get classLectures
   * @return classLectures
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getClassLectures() {
    return classLectures;
  }

  public void setClassLectures(Long classLectures) {
    this.classLectures = classLectures;
  }

  public LectureBreakupRequest createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public LectureBreakupRequest customChapter(Boolean customChapter) {
    this.customChapter = customChapter;
    return this;
  }

   /**
   * Get customChapter
   * @return customChapter
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomChapter() {
    return customChapter;
  }

  public void setCustomChapter(Boolean customChapter) {
    this.customChapter = customChapter;
  }

  public LectureBreakupRequest homeworkMin(Long homeworkMin) {
    this.homeworkMin = homeworkMin;
    return this;
  }

   /**
   * Get homeworkMin
   * @return homeworkMin
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getHomeworkMin() {
    return homeworkMin;
  }

  public void setHomeworkMin(Long homeworkMin) {
    this.homeworkMin = homeworkMin;
  }

  public LectureBreakupRequest isCopyOf(String isCopyOf) {
    this.isCopyOf = isCopyOf;
    return this;
  }

   /**
   * Get isCopyOf
   * @return isCopyOf
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsCopyOf() {
    return isCopyOf;
  }

  public void setIsCopyOf(String isCopyOf) {
    this.isCopyOf = isCopyOf;
  }

  public LectureBreakupRequest labLectures(Long labLectures) {
    this.labLectures = labLectures;
    return this;
  }

   /**
   * Get labLectures
   * @return labLectures
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLabLectures() {
    return labLectures;
  }

  public void setLabLectures(Long labLectures) {
    this.labLectures = labLectures;
  }

  public LectureBreakupRequest lectureBreakUpUuids(List<String> lectureBreakUpUuids) {
    this.lectureBreakUpUuids = lectureBreakUpUuids;
    return this;
  }

  public LectureBreakupRequest addLectureBreakUpUuidsItem(String lectureBreakUpUuidsItem) {
    this.lectureBreakUpUuids.add(lectureBreakUpUuidsItem);
    return this;
  }

   /**
   * Get lectureBreakUpUuids
   * @return lectureBreakUpUuids
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getLectureBreakUpUuids() {
    return lectureBreakUpUuids;
  }

  public void setLectureBreakUpUuids(List<String> lectureBreakUpUuids) {
    this.lectureBreakUpUuids = lectureBreakUpUuids;
  }

  public LectureBreakupRequest level(LevelEnum level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @ApiModelProperty(example = "null", value = "")
  public LevelEnum getLevel() {
    return level;
  }

  public void setLevel(LevelEnum level) {
    this.level = level;
  }

  public LectureBreakupRequest masterClass(Long masterClass) {
    this.masterClass = masterClass;
    return this;
  }

   /**
   * Get masterClass
   * @return masterClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMasterClass() {
    return masterClass;
  }

  public void setMasterClass(Long masterClass) {
    this.masterClass = masterClass;
  }

  public LectureBreakupRequest masterSubject(Long masterSubject) {
    this.masterSubject = masterSubject;
    return this;
  }

   /**
   * Get masterSubject
   * @return masterSubject
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMasterSubject() {
    return masterSubject;
  }

  public void setMasterSubject(Long masterSubject) {
    this.masterSubject = masterSubject;
  }

  public LectureBreakupRequest modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public LectureBreakupRequest section(Long section) {
    this.section = section;
    return this;
  }

   /**
   * Get section
   * @return section
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSection() {
    return section;
  }

  public void setSection(Long section) {
    this.section = section;
  }

  public LectureBreakupRequest seqNumber(Long seqNumber) {
    this.seqNumber = seqNumber;
    return this;
  }

   /**
   * Get seqNumber
   * @return seqNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSeqNumber() {
    return seqNumber;
  }

  public void setSeqNumber(Long seqNumber) {
    this.seqNumber = seqNumber;
  }

  public LectureBreakupRequest shareable(Boolean shareable) {
    this.shareable = shareable;
    return this;
  }

   /**
   * Get shareable
   * @return shareable
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShareable() {
    return shareable;
  }

  public void setShareable(Boolean shareable) {
    this.shareable = shareable;
  }

  public LectureBreakupRequest status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public LectureBreakupRequest user(Long user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUser() {
    return user;
  }

  public void setUser(Long user) {
    this.user = user;
  }

  public LectureBreakupRequest uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LectureBreakupRequest lectureBreakupRequest = (LectureBreakupRequest) o;
    return Objects.equals(this.academicSession, lectureBreakupRequest.academicSession) &&
        Objects.equals(this.branch, lectureBreakupRequest.branch) &&
        Objects.equals(this.chapterId, lectureBreakupRequest.chapterId) &&
        Objects.equals(this.classLectures, lectureBreakupRequest.classLectures) &&
        Objects.equals(this.createdBy, lectureBreakupRequest.createdBy) &&
        Objects.equals(this.customChapter, lectureBreakupRequest.customChapter) &&
        Objects.equals(this.homeworkMin, lectureBreakupRequest.homeworkMin) &&
        Objects.equals(this.isCopyOf, lectureBreakupRequest.isCopyOf) &&
        Objects.equals(this.labLectures, lectureBreakupRequest.labLectures) &&
        Objects.equals(this.lectureBreakUpUuids, lectureBreakupRequest.lectureBreakUpUuids) &&
        Objects.equals(this.level, lectureBreakupRequest.level) &&
        Objects.equals(this.masterClass, lectureBreakupRequest.masterClass) &&
        Objects.equals(this.masterSubject, lectureBreakupRequest.masterSubject) &&
        Objects.equals(this.modifiedBy, lectureBreakupRequest.modifiedBy) &&
        Objects.equals(this.section, lectureBreakupRequest.section) &&
        Objects.equals(this.seqNumber, lectureBreakupRequest.seqNumber) &&
        Objects.equals(this.shareable, lectureBreakupRequest.shareable) &&
        Objects.equals(this.status, lectureBreakupRequest.status) &&
        Objects.equals(this.user, lectureBreakupRequest.user) &&
        Objects.equals(this.uuid, lectureBreakupRequest.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(academicSession, branch, chapterId, classLectures, createdBy, customChapter, homeworkMin, isCopyOf, labLectures, lectureBreakUpUuids, level, masterClass, masterSubject, modifiedBy, section, seqNumber, shareable, status, user, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LectureBreakupRequest {\n");
    
    sb.append("    academicSession: ").append(toIndentedString(academicSession)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    chapterId: ").append(toIndentedString(chapterId)).append("\n");
    sb.append("    classLectures: ").append(toIndentedString(classLectures)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    customChapter: ").append(toIndentedString(customChapter)).append("\n");
    sb.append("    homeworkMin: ").append(toIndentedString(homeworkMin)).append("\n");
    sb.append("    isCopyOf: ").append(toIndentedString(isCopyOf)).append("\n");
    sb.append("    labLectures: ").append(toIndentedString(labLectures)).append("\n");
    sb.append("    lectureBreakUpUuids: ").append(toIndentedString(lectureBreakUpUuids)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    masterClass: ").append(toIndentedString(masterClass)).append("\n");
    sb.append("    masterSubject: ").append(toIndentedString(masterSubject)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    section: ").append(toIndentedString(section)).append("\n");
    sb.append("    seqNumber: ").append(toIndentedString(seqNumber)).append("\n");
    sb.append("    shareable: ").append(toIndentedString(shareable)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

