/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.QuestionConceptLOLDRequest;
import com.nexteducation.swagger.nextsws.model.QuestionRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * QuestionConceptAssessmentRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class QuestionConceptAssessmentRequest   {
  @SerializedName("assessmentIds")
  private List<String> assessmentIds = new ArrayList<String>();

  @SerializedName("question")
  private QuestionRequest question = null;

  @SerializedName("questionConcepts")
  private List<QuestionConceptLOLDRequest> questionConcepts = new ArrayList<QuestionConceptLOLDRequest>();

  public QuestionConceptAssessmentRequest assessmentIds(List<String> assessmentIds) {
    this.assessmentIds = assessmentIds;
    return this;
  }

  public QuestionConceptAssessmentRequest addAssessmentIdsItem(String assessmentIdsItem) {
    this.assessmentIds.add(assessmentIdsItem);
    return this;
  }

   /**
   * Get assessmentIds
   * @return assessmentIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAssessmentIds() {
    return assessmentIds;
  }

  public void setAssessmentIds(List<String> assessmentIds) {
    this.assessmentIds = assessmentIds;
  }

  public QuestionConceptAssessmentRequest question(QuestionRequest question) {
    this.question = question;
    return this;
  }

   /**
   * Get question
   * @return question
  **/
  @ApiModelProperty(example = "null", value = "")
  public QuestionRequest getQuestion() {
    return question;
  }

  public void setQuestion(QuestionRequest question) {
    this.question = question;
  }

  public QuestionConceptAssessmentRequest questionConcepts(List<QuestionConceptLOLDRequest> questionConcepts) {
    this.questionConcepts = questionConcepts;
    return this;
  }

  public QuestionConceptAssessmentRequest addQuestionConceptsItem(QuestionConceptLOLDRequest questionConceptsItem) {
    this.questionConcepts.add(questionConceptsItem);
    return this;
  }

   /**
   * Get questionConcepts
   * @return questionConcepts
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<QuestionConceptLOLDRequest> getQuestionConcepts() {
    return questionConcepts;
  }

  public void setQuestionConcepts(List<QuestionConceptLOLDRequest> questionConcepts) {
    this.questionConcepts = questionConcepts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuestionConceptAssessmentRequest questionConceptAssessmentRequest = (QuestionConceptAssessmentRequest) o;
    return Objects.equals(this.assessmentIds, questionConceptAssessmentRequest.assessmentIds) &&
        Objects.equals(this.question, questionConceptAssessmentRequest.question) &&
        Objects.equals(this.questionConcepts, questionConceptAssessmentRequest.questionConcepts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assessmentIds, question, questionConcepts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuestionConceptAssessmentRequest {\n");
    
    sb.append("    assessmentIds: ").append(toIndentedString(assessmentIds)).append("\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("    questionConcepts: ").append(toIndentedString(questionConcepts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

