/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.ResourceRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ResourceDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class ResourceDTO   {
  @SerializedName("bookPageNumber")
  private String bookPageNumber = null;

  @SerializedName("customResource")
  private Boolean customResource = null;

  @SerializedName("customResourceName")
  private String customResourceName = null;

  @SerializedName("customSyllabusNode")
  private Boolean customSyllabusNode = null;

  @SerializedName("globalResource")
  private Boolean globalResource = null;

  /**
   * Gets or Sets location
   */
  public enum LocationEnum {
    @SerializedName("Classroom")
    CLASSROOM("Classroom"),
    
    @SerializedName("Lab")
    LAB("Lab"),
    
    @SerializedName("Homework")
    HOMEWORK("Homework");

    private String value;

    LocationEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("location")
  private LocationEnum location = null;

  @SerializedName("nodeResourceId")
  private Long nodeResourceId = null;

  @SerializedName("resourceRequestList")
  private List<ResourceRequest> resourceRequestList = new ArrayList<ResourceRequest>();

  @SerializedName("resourceType")
  private String resourceType = null;

  @SerializedName("resourceUuid")
  private String resourceUuid = null;

  @SerializedName("sectionId")
  private Long sectionId = null;

  @SerializedName("sectionType")
  private Boolean sectionType = null;

  @SerializedName("sectiontype")
  private String sectiontype = null;

  @SerializedName("studyClassId")
  private Long studyClassId = null;

  @SerializedName("syllabusNode")
  private Long syllabusNode = null;

  public ResourceDTO bookPageNumber(String bookPageNumber) {
    this.bookPageNumber = bookPageNumber;
    return this;
  }

   /**
   * Get bookPageNumber
   * @return bookPageNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBookPageNumber() {
    return bookPageNumber;
  }

  public void setBookPageNumber(String bookPageNumber) {
    this.bookPageNumber = bookPageNumber;
  }

  public ResourceDTO customResource(Boolean customResource) {
    this.customResource = customResource;
    return this;
  }

   /**
   * Get customResource
   * @return customResource
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomResource() {
    return customResource;
  }

  public void setCustomResource(Boolean customResource) {
    this.customResource = customResource;
  }

  public ResourceDTO customResourceName(String customResourceName) {
    this.customResourceName = customResourceName;
    return this;
  }

   /**
   * Get customResourceName
   * @return customResourceName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomResourceName() {
    return customResourceName;
  }

  public void setCustomResourceName(String customResourceName) {
    this.customResourceName = customResourceName;
  }

  public ResourceDTO customSyllabusNode(Boolean customSyllabusNode) {
    this.customSyllabusNode = customSyllabusNode;
    return this;
  }

   /**
   * Get customSyllabusNode
   * @return customSyllabusNode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomSyllabusNode() {
    return customSyllabusNode;
  }

  public void setCustomSyllabusNode(Boolean customSyllabusNode) {
    this.customSyllabusNode = customSyllabusNode;
  }

  public ResourceDTO globalResource(Boolean globalResource) {
    this.globalResource = globalResource;
    return this;
  }

   /**
   * Get globalResource
   * @return globalResource
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getGlobalResource() {
    return globalResource;
  }

  public void setGlobalResource(Boolean globalResource) {
    this.globalResource = globalResource;
  }

  public ResourceDTO location(LocationEnum location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocationEnum getLocation() {
    return location;
  }

  public void setLocation(LocationEnum location) {
    this.location = location;
  }

  public ResourceDTO nodeResourceId(Long nodeResourceId) {
    this.nodeResourceId = nodeResourceId;
    return this;
  }

   /**
   * Get nodeResourceId
   * @return nodeResourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNodeResourceId() {
    return nodeResourceId;
  }

  public void setNodeResourceId(Long nodeResourceId) {
    this.nodeResourceId = nodeResourceId;
  }

  public ResourceDTO resourceRequestList(List<ResourceRequest> resourceRequestList) {
    this.resourceRequestList = resourceRequestList;
    return this;
  }

  public ResourceDTO addResourceRequestListItem(ResourceRequest resourceRequestListItem) {
    this.resourceRequestList.add(resourceRequestListItem);
    return this;
  }

   /**
   * Get resourceRequestList
   * @return resourceRequestList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ResourceRequest> getResourceRequestList() {
    return resourceRequestList;
  }

  public void setResourceRequestList(List<ResourceRequest> resourceRequestList) {
    this.resourceRequestList = resourceRequestList;
  }

  public ResourceDTO resourceType(String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }

  public ResourceDTO resourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
    return this;
  }

   /**
   * Get resourceUuid
   * @return resourceUuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResourceUuid() {
    return resourceUuid;
  }

  public void setResourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
  }

  public ResourceDTO sectionId(Long sectionId) {
    this.sectionId = sectionId;
    return this;
  }

   /**
   * Get sectionId
   * @return sectionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSectionId() {
    return sectionId;
  }

  public void setSectionId(Long sectionId) {
    this.sectionId = sectionId;
  }

  public ResourceDTO sectionType(Boolean sectionType) {
    this.sectionType = sectionType;
    return this;
  }

   /**
   * Get sectionType
   * @return sectionType
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSectionType() {
    return sectionType;
  }

  public void setSectionType(Boolean sectionType) {
    this.sectionType = sectionType;
  }

  public ResourceDTO sectiontype(String sectiontype) {
    this.sectiontype = sectiontype;
    return this;
  }

   /**
   * Get sectiontype
   * @return sectiontype
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSectiontype() {
    return sectiontype;
  }

  public void setSectiontype(String sectiontype) {
    this.sectiontype = sectiontype;
  }

  public ResourceDTO studyClassId(Long studyClassId) {
    this.studyClassId = studyClassId;
    return this;
  }

   /**
   * Get studyClassId
   * @return studyClassId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStudyClassId() {
    return studyClassId;
  }

  public void setStudyClassId(Long studyClassId) {
    this.studyClassId = studyClassId;
  }

  public ResourceDTO syllabusNode(Long syllabusNode) {
    this.syllabusNode = syllabusNode;
    return this;
  }

   /**
   * Get syllabusNode
   * @return syllabusNode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSyllabusNode() {
    return syllabusNode;
  }

  public void setSyllabusNode(Long syllabusNode) {
    this.syllabusNode = syllabusNode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceDTO resourceDTO = (ResourceDTO) o;
    return Objects.equals(this.bookPageNumber, resourceDTO.bookPageNumber) &&
        Objects.equals(this.customResource, resourceDTO.customResource) &&
        Objects.equals(this.customResourceName, resourceDTO.customResourceName) &&
        Objects.equals(this.customSyllabusNode, resourceDTO.customSyllabusNode) &&
        Objects.equals(this.globalResource, resourceDTO.globalResource) &&
        Objects.equals(this.location, resourceDTO.location) &&
        Objects.equals(this.nodeResourceId, resourceDTO.nodeResourceId) &&
        Objects.equals(this.resourceRequestList, resourceDTO.resourceRequestList) &&
        Objects.equals(this.resourceType, resourceDTO.resourceType) &&
        Objects.equals(this.resourceUuid, resourceDTO.resourceUuid) &&
        Objects.equals(this.sectionId, resourceDTO.sectionId) &&
        Objects.equals(this.sectionType, resourceDTO.sectionType) &&
        Objects.equals(this.sectiontype, resourceDTO.sectiontype) &&
        Objects.equals(this.studyClassId, resourceDTO.studyClassId) &&
        Objects.equals(this.syllabusNode, resourceDTO.syllabusNode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookPageNumber, customResource, customResourceName, customSyllabusNode, globalResource, location, nodeResourceId, resourceRequestList, resourceType, resourceUuid, sectionId, sectionType, sectiontype, studyClassId, syllabusNode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceDTO {\n");
    
    sb.append("    bookPageNumber: ").append(toIndentedString(bookPageNumber)).append("\n");
    sb.append("    customResource: ").append(toIndentedString(customResource)).append("\n");
    sb.append("    customResourceName: ").append(toIndentedString(customResourceName)).append("\n");
    sb.append("    customSyllabusNode: ").append(toIndentedString(customSyllabusNode)).append("\n");
    sb.append("    globalResource: ").append(toIndentedString(globalResource)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    nodeResourceId: ").append(toIndentedString(nodeResourceId)).append("\n");
    sb.append("    resourceRequestList: ").append(toIndentedString(resourceRequestList)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    resourceUuid: ").append(toIndentedString(resourceUuid)).append("\n");
    sb.append("    sectionId: ").append(toIndentedString(sectionId)).append("\n");
    sb.append("    sectionType: ").append(toIndentedString(sectionType)).append("\n");
    sb.append("    sectiontype: ").append(toIndentedString(sectiontype)).append("\n");
    sb.append("    studyClassId: ").append(toIndentedString(studyClassId)).append("\n");
    sb.append("    syllabusNode: ").append(toIndentedString(syllabusNode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

