/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.AssessmentShortResponse;
import com.nexteducation.swagger.nextsws.model.SyllabusResponseV2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ShortAssessmentWithSyllabusResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class ShortAssessmentWithSyllabusResponse   {
  @SerializedName("assessmentShortResponse")
  private AssessmentShortResponse assessmentShortResponse = null;

  @SerializedName("syllabusResponse")
  private SyllabusResponseV2 syllabusResponse = null;

  public ShortAssessmentWithSyllabusResponse assessmentShortResponse(AssessmentShortResponse assessmentShortResponse) {
    this.assessmentShortResponse = assessmentShortResponse;
    return this;
  }

   /**
   * Get assessmentShortResponse
   * @return assessmentShortResponse
  **/
  @ApiModelProperty(example = "null", value = "")
  public AssessmentShortResponse getAssessmentShortResponse() {
    return assessmentShortResponse;
  }

  public void setAssessmentShortResponse(AssessmentShortResponse assessmentShortResponse) {
    this.assessmentShortResponse = assessmentShortResponse;
  }

  public ShortAssessmentWithSyllabusResponse syllabusResponse(SyllabusResponseV2 syllabusResponse) {
    this.syllabusResponse = syllabusResponse;
    return this;
  }

   /**
   * Get syllabusResponse
   * @return syllabusResponse
  **/
  @ApiModelProperty(example = "null", value = "")
  public SyllabusResponseV2 getSyllabusResponse() {
    return syllabusResponse;
  }

  public void setSyllabusResponse(SyllabusResponseV2 syllabusResponse) {
    this.syllabusResponse = syllabusResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShortAssessmentWithSyllabusResponse shortAssessmentWithSyllabusResponse = (ShortAssessmentWithSyllabusResponse) o;
    return Objects.equals(this.assessmentShortResponse, shortAssessmentWithSyllabusResponse.assessmentShortResponse) &&
        Objects.equals(this.syllabusResponse, shortAssessmentWithSyllabusResponse.syllabusResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assessmentShortResponse, syllabusResponse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShortAssessmentWithSyllabusResponse {\n");
    
    sb.append("    assessmentShortResponse: ").append(toIndentedString(assessmentShortResponse)).append("\n");
    sb.append("    syllabusResponse: ").append(toIndentedString(syllabusResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

