/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SubjectAndSyllabusResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class SubjectAndSyllabusResponse   {
  @SerializedName("boardId")
  private Long boardId = null;

  @SerializedName("custom")
  private Boolean custom = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ncert")
  private Boolean ncert = null;

  @SerializedName("schoolSubjectId")
  private Long schoolSubjectId = null;

  @SerializedName("schoolSubjectName")
  private String schoolSubjectName = null;

  @SerializedName("seqNo")
  private Long seqNo = null;

  @SerializedName("signature")
  private String signature = null;

  @SerializedName("studyClassId")
  private Long studyClassId = null;

  @SerializedName("subjectId")
  private Long subjectId = null;

  @SerializedName("subjectName")
  private String subjectName = null;

  @SerializedName("type")
  private String type = null;

  public SubjectAndSyllabusResponse boardId(Long boardId) {
    this.boardId = boardId;
    return this;
  }

   /**
   * Get boardId
   * @return boardId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBoardId() {
    return boardId;
  }

  public void setBoardId(Long boardId) {
    this.boardId = boardId;
  }

  public SubjectAndSyllabusResponse custom(Boolean custom) {
    this.custom = custom;
    return this;
  }

   /**
   * Get custom
   * @return custom
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustom() {
    return custom;
  }

  public void setCustom(Boolean custom) {
    this.custom = custom;
  }

  public SubjectAndSyllabusResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SubjectAndSyllabusResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SubjectAndSyllabusResponse ncert(Boolean ncert) {
    this.ncert = ncert;
    return this;
  }

   /**
   * Get ncert
   * @return ncert
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getNcert() {
    return ncert;
  }

  public void setNcert(Boolean ncert) {
    this.ncert = ncert;
  }

  public SubjectAndSyllabusResponse schoolSubjectId(Long schoolSubjectId) {
    this.schoolSubjectId = schoolSubjectId;
    return this;
  }

   /**
   * Get schoolSubjectId
   * @return schoolSubjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSchoolSubjectId() {
    return schoolSubjectId;
  }

  public void setSchoolSubjectId(Long schoolSubjectId) {
    this.schoolSubjectId = schoolSubjectId;
  }

  public SubjectAndSyllabusResponse schoolSubjectName(String schoolSubjectName) {
    this.schoolSubjectName = schoolSubjectName;
    return this;
  }

   /**
   * Get schoolSubjectName
   * @return schoolSubjectName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSchoolSubjectName() {
    return schoolSubjectName;
  }

  public void setSchoolSubjectName(String schoolSubjectName) {
    this.schoolSubjectName = schoolSubjectName;
  }

  public SubjectAndSyllabusResponse seqNo(Long seqNo) {
    this.seqNo = seqNo;
    return this;
  }

   /**
   * Get seqNo
   * @return seqNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSeqNo() {
    return seqNo;
  }

  public void setSeqNo(Long seqNo) {
    this.seqNo = seqNo;
  }

  public SubjectAndSyllabusResponse signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }

  public SubjectAndSyllabusResponse studyClassId(Long studyClassId) {
    this.studyClassId = studyClassId;
    return this;
  }

   /**
   * Get studyClassId
   * @return studyClassId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStudyClassId() {
    return studyClassId;
  }

  public void setStudyClassId(Long studyClassId) {
    this.studyClassId = studyClassId;
  }

  public SubjectAndSyllabusResponse subjectId(Long subjectId) {
    this.subjectId = subjectId;
    return this;
  }

   /**
   * Get subjectId
   * @return subjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSubjectId() {
    return subjectId;
  }

  public void setSubjectId(Long subjectId) {
    this.subjectId = subjectId;
  }

  public SubjectAndSyllabusResponse subjectName(String subjectName) {
    this.subjectName = subjectName;
    return this;
  }

   /**
   * Get subjectName
   * @return subjectName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubjectName() {
    return subjectName;
  }

  public void setSubjectName(String subjectName) {
    this.subjectName = subjectName;
  }

  public SubjectAndSyllabusResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectAndSyllabusResponse subjectAndSyllabusResponse = (SubjectAndSyllabusResponse) o;
    return Objects.equals(this.boardId, subjectAndSyllabusResponse.boardId) &&
        Objects.equals(this.custom, subjectAndSyllabusResponse.custom) &&
        Objects.equals(this.id, subjectAndSyllabusResponse.id) &&
        Objects.equals(this.name, subjectAndSyllabusResponse.name) &&
        Objects.equals(this.ncert, subjectAndSyllabusResponse.ncert) &&
        Objects.equals(this.schoolSubjectId, subjectAndSyllabusResponse.schoolSubjectId) &&
        Objects.equals(this.schoolSubjectName, subjectAndSyllabusResponse.schoolSubjectName) &&
        Objects.equals(this.seqNo, subjectAndSyllabusResponse.seqNo) &&
        Objects.equals(this.signature, subjectAndSyllabusResponse.signature) &&
        Objects.equals(this.studyClassId, subjectAndSyllabusResponse.studyClassId) &&
        Objects.equals(this.subjectId, subjectAndSyllabusResponse.subjectId) &&
        Objects.equals(this.subjectName, subjectAndSyllabusResponse.subjectName) &&
        Objects.equals(this.type, subjectAndSyllabusResponse.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boardId, custom, id, name, ncert, schoolSubjectId, schoolSubjectName, seqNo, signature, studyClassId, subjectId, subjectName, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectAndSyllabusResponse {\n");
    
    sb.append("    boardId: ").append(toIndentedString(boardId)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ncert: ").append(toIndentedString(ncert)).append("\n");
    sb.append("    schoolSubjectId: ").append(toIndentedString(schoolSubjectId)).append("\n");
    sb.append("    schoolSubjectName: ").append(toIndentedString(schoolSubjectName)).append("\n");
    sb.append("    seqNo: ").append(toIndentedString(seqNo)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    studyClassId: ").append(toIndentedString(studyClassId)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    subjectName: ").append(toIndentedString(subjectName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

