/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.SubjectGroupResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * SubjectResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T11:28:33.033+05:30")
public class SubjectResponse   {
  @SerializedName("academicSessionId")
  private Long academicSessionId = null;

  @SerializedName("branchId")
  private Long branchId = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("createdOn")
  private DateTime createdOn = null;

  @SerializedName("hasPracticals")
  private Boolean hasPracticals = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("ifAllied")
  private Boolean ifAllied = null;

  @SerializedName("ifDefaultActivityMap")
  private Boolean ifDefaultActivityMap = null;

  @SerializedName("isMandatory")
  private Boolean isMandatory = null;

  @SerializedName("maxAllowed")
  private Integer maxAllowed = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("modifiedOn")
  private DateTime modifiedOn = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("noOfPeriodOfPractical")
  private Integer noOfPeriodOfPractical = null;

  @SerializedName("noOfPeriodOfTheory")
  private Integer noOfPeriodOfTheory = null;

  @SerializedName("parentSubjectId")
  private Long parentSubjectId = null;

  @SerializedName("studyClassId")
  private Long studyClassId = null;

  @SerializedName("subjectGroup")
  private SubjectGroupResponse subjectGroup = null;

  /**
   * Gets or Sets subjectType
   */
  public enum SubjectTypeEnum {
    @SerializedName("AdmissionSubjects")
    ADMISSIONSUBJECTS("AdmissionSubjects"),
    
    @SerializedName("Scholastic")
    SCHOLASTIC("Scholastic"),
    
    @SerializedName("CoScholastic")
    COSCHOLASTIC("CoScholastic"),
    
    @SerializedName("ActivitySubject")
    ACTIVITYSUBJECT("ActivitySubject");

    private String value;

    SubjectTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("subjectType")
  private SubjectTypeEnum subjectType = null;

  @SerializedName("tnMasterSubjectId")
  private Long tnMasterSubjectId = null;

  public SubjectResponse academicSessionId(Long academicSessionId) {
    this.academicSessionId = academicSessionId;
    return this;
  }

   /**
   * Get academicSessionId
   * @return academicSessionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAcademicSessionId() {
    return academicSessionId;
  }

  public void setAcademicSessionId(Long academicSessionId) {
    this.academicSessionId = academicSessionId;
  }

  public SubjectResponse branchId(Long branchId) {
    this.branchId = branchId;
    return this;
  }

   /**
   * Get branchId
   * @return branchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchId() {
    return branchId;
  }

  public void setBranchId(Long branchId) {
    this.branchId = branchId;
  }

  public SubjectResponse code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public SubjectResponse createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public SubjectResponse createdOn(DateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(DateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SubjectResponse hasPracticals(Boolean hasPracticals) {
    this.hasPracticals = hasPracticals;
    return this;
  }

   /**
   * Get hasPracticals
   * @return hasPracticals
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHasPracticals() {
    return hasPracticals;
  }

  public void setHasPracticals(Boolean hasPracticals) {
    this.hasPracticals = hasPracticals;
  }

  public SubjectResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SubjectResponse ifAllied(Boolean ifAllied) {
    this.ifAllied = ifAllied;
    return this;
  }

   /**
   * Get ifAllied
   * @return ifAllied
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIfAllied() {
    return ifAllied;
  }

  public void setIfAllied(Boolean ifAllied) {
    this.ifAllied = ifAllied;
  }

  public SubjectResponse ifDefaultActivityMap(Boolean ifDefaultActivityMap) {
    this.ifDefaultActivityMap = ifDefaultActivityMap;
    return this;
  }

   /**
   * Get ifDefaultActivityMap
   * @return ifDefaultActivityMap
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIfDefaultActivityMap() {
    return ifDefaultActivityMap;
  }

  public void setIfDefaultActivityMap(Boolean ifDefaultActivityMap) {
    this.ifDefaultActivityMap = ifDefaultActivityMap;
  }

  public SubjectResponse isMandatory(Boolean isMandatory) {
    this.isMandatory = isMandatory;
    return this;
  }

   /**
   * Get isMandatory
   * @return isMandatory
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsMandatory() {
    return isMandatory;
  }

  public void setIsMandatory(Boolean isMandatory) {
    this.isMandatory = isMandatory;
  }

  public SubjectResponse maxAllowed(Integer maxAllowed) {
    this.maxAllowed = maxAllowed;
    return this;
  }

   /**
   * Get maxAllowed
   * @return maxAllowed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMaxAllowed() {
    return maxAllowed;
  }

  public void setMaxAllowed(Integer maxAllowed) {
    this.maxAllowed = maxAllowed;
  }

  public SubjectResponse modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public SubjectResponse modifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * Get modifiedOn
   * @return modifiedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }

  public SubjectResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SubjectResponse noOfPeriodOfPractical(Integer noOfPeriodOfPractical) {
    this.noOfPeriodOfPractical = noOfPeriodOfPractical;
    return this;
  }

   /**
   * Get noOfPeriodOfPractical
   * @return noOfPeriodOfPractical
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNoOfPeriodOfPractical() {
    return noOfPeriodOfPractical;
  }

  public void setNoOfPeriodOfPractical(Integer noOfPeriodOfPractical) {
    this.noOfPeriodOfPractical = noOfPeriodOfPractical;
  }

  public SubjectResponse noOfPeriodOfTheory(Integer noOfPeriodOfTheory) {
    this.noOfPeriodOfTheory = noOfPeriodOfTheory;
    return this;
  }

   /**
   * Get noOfPeriodOfTheory
   * @return noOfPeriodOfTheory
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNoOfPeriodOfTheory() {
    return noOfPeriodOfTheory;
  }

  public void setNoOfPeriodOfTheory(Integer noOfPeriodOfTheory) {
    this.noOfPeriodOfTheory = noOfPeriodOfTheory;
  }

  public SubjectResponse parentSubjectId(Long parentSubjectId) {
    this.parentSubjectId = parentSubjectId;
    return this;
  }

   /**
   * Get parentSubjectId
   * @return parentSubjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getParentSubjectId() {
    return parentSubjectId;
  }

  public void setParentSubjectId(Long parentSubjectId) {
    this.parentSubjectId = parentSubjectId;
  }

  public SubjectResponse studyClassId(Long studyClassId) {
    this.studyClassId = studyClassId;
    return this;
  }

   /**
   * Get studyClassId
   * @return studyClassId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStudyClassId() {
    return studyClassId;
  }

  public void setStudyClassId(Long studyClassId) {
    this.studyClassId = studyClassId;
  }

  public SubjectResponse subjectGroup(SubjectGroupResponse subjectGroup) {
    this.subjectGroup = subjectGroup;
    return this;
  }

   /**
   * Get subjectGroup
   * @return subjectGroup
  **/
  @ApiModelProperty(example = "null", value = "")
  public SubjectGroupResponse getSubjectGroup() {
    return subjectGroup;
  }

  public void setSubjectGroup(SubjectGroupResponse subjectGroup) {
    this.subjectGroup = subjectGroup;
  }

  public SubjectResponse subjectType(SubjectTypeEnum subjectType) {
    this.subjectType = subjectType;
    return this;
  }

   /**
   * Get subjectType
   * @return subjectType
  **/
  @ApiModelProperty(example = "null", value = "")
  public SubjectTypeEnum getSubjectType() {
    return subjectType;
  }

  public void setSubjectType(SubjectTypeEnum subjectType) {
    this.subjectType = subjectType;
  }

  public SubjectResponse tnMasterSubjectId(Long tnMasterSubjectId) {
    this.tnMasterSubjectId = tnMasterSubjectId;
    return this;
  }

   /**
   * Get tnMasterSubjectId
   * @return tnMasterSubjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTnMasterSubjectId() {
    return tnMasterSubjectId;
  }

  public void setTnMasterSubjectId(Long tnMasterSubjectId) {
    this.tnMasterSubjectId = tnMasterSubjectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectResponse subjectResponse = (SubjectResponse) o;
    return Objects.equals(this.academicSessionId, subjectResponse.academicSessionId) &&
        Objects.equals(this.branchId, subjectResponse.branchId) &&
        Objects.equals(this.code, subjectResponse.code) &&
        Objects.equals(this.createdBy, subjectResponse.createdBy) &&
        Objects.equals(this.createdOn, subjectResponse.createdOn) &&
        Objects.equals(this.hasPracticals, subjectResponse.hasPracticals) &&
        Objects.equals(this.id, subjectResponse.id) &&
        Objects.equals(this.ifAllied, subjectResponse.ifAllied) &&
        Objects.equals(this.ifDefaultActivityMap, subjectResponse.ifDefaultActivityMap) &&
        Objects.equals(this.isMandatory, subjectResponse.isMandatory) &&
        Objects.equals(this.maxAllowed, subjectResponse.maxAllowed) &&
        Objects.equals(this.modifiedBy, subjectResponse.modifiedBy) &&
        Objects.equals(this.modifiedOn, subjectResponse.modifiedOn) &&
        Objects.equals(this.name, subjectResponse.name) &&
        Objects.equals(this.noOfPeriodOfPractical, subjectResponse.noOfPeriodOfPractical) &&
        Objects.equals(this.noOfPeriodOfTheory, subjectResponse.noOfPeriodOfTheory) &&
        Objects.equals(this.parentSubjectId, subjectResponse.parentSubjectId) &&
        Objects.equals(this.studyClassId, subjectResponse.studyClassId) &&
        Objects.equals(this.subjectGroup, subjectResponse.subjectGroup) &&
        Objects.equals(this.subjectType, subjectResponse.subjectType) &&
        Objects.equals(this.tnMasterSubjectId, subjectResponse.tnMasterSubjectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(academicSessionId, branchId, code, createdBy, createdOn, hasPracticals, id, ifAllied, ifDefaultActivityMap, isMandatory, maxAllowed, modifiedBy, modifiedOn, name, noOfPeriodOfPractical, noOfPeriodOfTheory, parentSubjectId, studyClassId, subjectGroup, subjectType, tnMasterSubjectId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectResponse {\n");
    
    sb.append("    academicSessionId: ").append(toIndentedString(academicSessionId)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    hasPracticals: ").append(toIndentedString(hasPracticals)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ifAllied: ").append(toIndentedString(ifAllied)).append("\n");
    sb.append("    ifDefaultActivityMap: ").append(toIndentedString(ifDefaultActivityMap)).append("\n");
    sb.append("    isMandatory: ").append(toIndentedString(isMandatory)).append("\n");
    sb.append("    maxAllowed: ").append(toIndentedString(maxAllowed)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    noOfPeriodOfPractical: ").append(toIndentedString(noOfPeriodOfPractical)).append("\n");
    sb.append("    noOfPeriodOfTheory: ").append(toIndentedString(noOfPeriodOfTheory)).append("\n");
    sb.append("    parentSubjectId: ").append(toIndentedString(parentSubjectId)).append("\n");
    sb.append("    studyClassId: ").append(toIndentedString(studyClassId)).append("\n");
    sb.append("    subjectGroup: ").append(toIndentedString(subjectGroup)).append("\n");
    sb.append("    subjectType: ").append(toIndentedString(subjectType)).append("\n");
    sb.append("    tnMasterSubjectId: ").append(toIndentedString(tnMasterSubjectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

