/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * AssignmentAttachmentResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class AssignmentAttachmentResponse   {
  @SerializedName("assetUUID")
  private String assetUUID = null;

  @SerializedName("assignmentUUID")
  private String assignmentUUID = null;

  @SerializedName("branchId")
  private Long branchId = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("createdOn")
  private DateTime createdOn = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("modifiedOn")
  private DateTime modifiedOn = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("InActive")
    INACTIVE("InActive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("uuid")
  private String uuid = null;

  public AssignmentAttachmentResponse assetUUID(String assetUUID) {
    this.assetUUID = assetUUID;
    return this;
  }

   /**
   * Get assetUUID
   * @return assetUUID
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAssetUUID() {
    return assetUUID;
  }

  public void setAssetUUID(String assetUUID) {
    this.assetUUID = assetUUID;
  }

  public AssignmentAttachmentResponse assignmentUUID(String assignmentUUID) {
    this.assignmentUUID = assignmentUUID;
    return this;
  }

   /**
   * Get assignmentUUID
   * @return assignmentUUID
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAssignmentUUID() {
    return assignmentUUID;
  }

  public void setAssignmentUUID(String assignmentUUID) {
    this.assignmentUUID = assignmentUUID;
  }

  public AssignmentAttachmentResponse branchId(Long branchId) {
    this.branchId = branchId;
    return this;
  }

   /**
   * Get branchId
   * @return branchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchId() {
    return branchId;
  }

  public void setBranchId(Long branchId) {
    this.branchId = branchId;
  }

  public AssignmentAttachmentResponse createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public AssignmentAttachmentResponse createdOn(DateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(DateTime createdOn) {
    this.createdOn = createdOn;
  }

  public AssignmentAttachmentResponse modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public AssignmentAttachmentResponse modifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * Get modifiedOn
   * @return modifiedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }

  public AssignmentAttachmentResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AssignmentAttachmentResponse uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignmentAttachmentResponse assignmentAttachmentResponse = (AssignmentAttachmentResponse) o;
    return Objects.equals(this.assetUUID, assignmentAttachmentResponse.assetUUID) &&
        Objects.equals(this.assignmentUUID, assignmentAttachmentResponse.assignmentUUID) &&
        Objects.equals(this.branchId, assignmentAttachmentResponse.branchId) &&
        Objects.equals(this.createdBy, assignmentAttachmentResponse.createdBy) &&
        Objects.equals(this.createdOn, assignmentAttachmentResponse.createdOn) &&
        Objects.equals(this.modifiedBy, assignmentAttachmentResponse.modifiedBy) &&
        Objects.equals(this.modifiedOn, assignmentAttachmentResponse.modifiedOn) &&
        Objects.equals(this.status, assignmentAttachmentResponse.status) &&
        Objects.equals(this.uuid, assignmentAttachmentResponse.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetUUID, assignmentUUID, branchId, createdBy, createdOn, modifiedBy, modifiedOn, status, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignmentAttachmentResponse {\n");
    
    sb.append("    assetUUID: ").append(toIndentedString(assetUUID)).append("\n");
    sb.append("    assignmentUUID: ").append(toIndentedString(assignmentUUID)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

