/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.AssignmentAttachmentRequest;
import com.nexteducation.swagger.nextsws.model.AssignmentSubmissionRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * AssignmentRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class AssignmentRequest   {
  @SerializedName("attachmentsRequest")
  private List<AssignmentAttachmentRequest> attachmentsRequest = new ArrayList<AssignmentAttachmentRequest>();

  @SerializedName("branchId")
  private Long branchId = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("resourceUuid")
  private String resourceUuid = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("InActive")
    INACTIVE("InActive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("submissionsRequest")
  private List<AssignmentSubmissionRequest> submissionsRequest = new ArrayList<AssignmentSubmissionRequest>();

  @SerializedName("uuid")
  private String uuid = null;

  public AssignmentRequest attachmentsRequest(List<AssignmentAttachmentRequest> attachmentsRequest) {
    this.attachmentsRequest = attachmentsRequest;
    return this;
  }

  public AssignmentRequest addAttachmentsRequestItem(AssignmentAttachmentRequest attachmentsRequestItem) {
    this.attachmentsRequest.add(attachmentsRequestItem);
    return this;
  }

   /**
   * Get attachmentsRequest
   * @return attachmentsRequest
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AssignmentAttachmentRequest> getAttachmentsRequest() {
    return attachmentsRequest;
  }

  public void setAttachmentsRequest(List<AssignmentAttachmentRequest> attachmentsRequest) {
    this.attachmentsRequest = attachmentsRequest;
  }

  public AssignmentRequest branchId(Long branchId) {
    this.branchId = branchId;
    return this;
  }

   /**
   * Get branchId
   * @return branchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchId() {
    return branchId;
  }

  public void setBranchId(Long branchId) {
    this.branchId = branchId;
  }

  public AssignmentRequest createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public AssignmentRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AssignmentRequest id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AssignmentRequest modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public AssignmentRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AssignmentRequest resourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
    return this;
  }

   /**
   * Get resourceUuid
   * @return resourceUuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResourceUuid() {
    return resourceUuid;
  }

  public void setResourceUuid(String resourceUuid) {
    this.resourceUuid = resourceUuid;
  }

  public AssignmentRequest status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AssignmentRequest submissionsRequest(List<AssignmentSubmissionRequest> submissionsRequest) {
    this.submissionsRequest = submissionsRequest;
    return this;
  }

  public AssignmentRequest addSubmissionsRequestItem(AssignmentSubmissionRequest submissionsRequestItem) {
    this.submissionsRequest.add(submissionsRequestItem);
    return this;
  }

   /**
   * Get submissionsRequest
   * @return submissionsRequest
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AssignmentSubmissionRequest> getSubmissionsRequest() {
    return submissionsRequest;
  }

  public void setSubmissionsRequest(List<AssignmentSubmissionRequest> submissionsRequest) {
    this.submissionsRequest = submissionsRequest;
  }

  public AssignmentRequest uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignmentRequest assignmentRequest = (AssignmentRequest) o;
    return Objects.equals(this.attachmentsRequest, assignmentRequest.attachmentsRequest) &&
        Objects.equals(this.branchId, assignmentRequest.branchId) &&
        Objects.equals(this.createdBy, assignmentRequest.createdBy) &&
        Objects.equals(this.description, assignmentRequest.description) &&
        Objects.equals(this.id, assignmentRequest.id) &&
        Objects.equals(this.modifiedBy, assignmentRequest.modifiedBy) &&
        Objects.equals(this.name, assignmentRequest.name) &&
        Objects.equals(this.resourceUuid, assignmentRequest.resourceUuid) &&
        Objects.equals(this.status, assignmentRequest.status) &&
        Objects.equals(this.submissionsRequest, assignmentRequest.submissionsRequest) &&
        Objects.equals(this.uuid, assignmentRequest.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachmentsRequest, branchId, createdBy, description, id, modifiedBy, name, resourceUuid, status, submissionsRequest, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignmentRequest {\n");
    
    sb.append("    attachmentsRequest: ").append(toIndentedString(attachmentsRequest)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    resourceUuid: ").append(toIndentedString(resourceUuid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    submissionsRequest: ").append(toIndentedString(submissionsRequest)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

