/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * ConceptSubjectResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class ConceptSubjectResponse   {
  @SerializedName("branchID")
  private Long branchID = null;

  @SerializedName("conceptID")
  private String conceptID = null;

  @SerializedName("conceptName")
  private String conceptName = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("createdOn")
  private DateTime createdOn = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("modifiedOn")
  private DateTime modifiedOn = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("InActive")
    INACTIVE("InActive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("subjectDescription")
  private String subjectDescription = null;

  @SerializedName("subjectID")
  private Long subjectID = null;

  @SerializedName("subjectName")
  private String subjectName = null;

  public ConceptSubjectResponse branchID(Long branchID) {
    this.branchID = branchID;
    return this;
  }

   /**
   * Get branchID
   * @return branchID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchID() {
    return branchID;
  }

  public void setBranchID(Long branchID) {
    this.branchID = branchID;
  }

  public ConceptSubjectResponse conceptID(String conceptID) {
    this.conceptID = conceptID;
    return this;
  }

   /**
   * Get conceptID
   * @return conceptID
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getConceptID() {
    return conceptID;
  }

  public void setConceptID(String conceptID) {
    this.conceptID = conceptID;
  }

  public ConceptSubjectResponse conceptName(String conceptName) {
    this.conceptName = conceptName;
    return this;
  }

   /**
   * Get conceptName
   * @return conceptName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getConceptName() {
    return conceptName;
  }

  public void setConceptName(String conceptName) {
    this.conceptName = conceptName;
  }

  public ConceptSubjectResponse createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public ConceptSubjectResponse createdOn(DateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(DateTime createdOn) {
    this.createdOn = createdOn;
  }

  public ConceptSubjectResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ConceptSubjectResponse modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public ConceptSubjectResponse modifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * Get modifiedOn
   * @return modifiedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(DateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }

  public ConceptSubjectResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ConceptSubjectResponse subjectDescription(String subjectDescription) {
    this.subjectDescription = subjectDescription;
    return this;
  }

   /**
   * Get subjectDescription
   * @return subjectDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubjectDescription() {
    return subjectDescription;
  }

  public void setSubjectDescription(String subjectDescription) {
    this.subjectDescription = subjectDescription;
  }

  public ConceptSubjectResponse subjectID(Long subjectID) {
    this.subjectID = subjectID;
    return this;
  }

   /**
   * Get subjectID
   * @return subjectID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSubjectID() {
    return subjectID;
  }

  public void setSubjectID(Long subjectID) {
    this.subjectID = subjectID;
  }

  public ConceptSubjectResponse subjectName(String subjectName) {
    this.subjectName = subjectName;
    return this;
  }

   /**
   * Get subjectName
   * @return subjectName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubjectName() {
    return subjectName;
  }

  public void setSubjectName(String subjectName) {
    this.subjectName = subjectName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConceptSubjectResponse conceptSubjectResponse = (ConceptSubjectResponse) o;
    return Objects.equals(this.branchID, conceptSubjectResponse.branchID) &&
        Objects.equals(this.conceptID, conceptSubjectResponse.conceptID) &&
        Objects.equals(this.conceptName, conceptSubjectResponse.conceptName) &&
        Objects.equals(this.createdBy, conceptSubjectResponse.createdBy) &&
        Objects.equals(this.createdOn, conceptSubjectResponse.createdOn) &&
        Objects.equals(this.id, conceptSubjectResponse.id) &&
        Objects.equals(this.modifiedBy, conceptSubjectResponse.modifiedBy) &&
        Objects.equals(this.modifiedOn, conceptSubjectResponse.modifiedOn) &&
        Objects.equals(this.status, conceptSubjectResponse.status) &&
        Objects.equals(this.subjectDescription, conceptSubjectResponse.subjectDescription) &&
        Objects.equals(this.subjectID, conceptSubjectResponse.subjectID) &&
        Objects.equals(this.subjectName, conceptSubjectResponse.subjectName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(branchID, conceptID, conceptName, createdBy, createdOn, id, modifiedBy, modifiedOn, status, subjectDescription, subjectID, subjectName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConceptSubjectResponse {\n");
    
    sb.append("    branchID: ").append(toIndentedString(branchID)).append("\n");
    sb.append("    conceptID: ").append(toIndentedString(conceptID)).append("\n");
    sb.append("    conceptName: ").append(toIndentedString(conceptName)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    subjectDescription: ").append(toIndentedString(subjectDescription)).append("\n");
    sb.append("    subjectID: ").append(toIndentedString(subjectID)).append("\n");
    sb.append("    subjectName: ").append(toIndentedString(subjectName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

