/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * MasterStudyClassDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class MasterStudyClassDTO   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("masterClasstId")
  private Long masterClasstId = null;

  @SerializedName("masterSubjectId")
  private Long masterSubjectId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("seqNo")
  private Long seqNo = null;

  @SerializedName("userBased")
  private Boolean userBased = null;

  public MasterStudyClassDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public MasterStudyClassDTO masterClasstId(Long masterClasstId) {
    this.masterClasstId = masterClasstId;
    return this;
  }

   /**
   * Get masterClasstId
   * @return masterClasstId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMasterClasstId() {
    return masterClasstId;
  }

  public void setMasterClasstId(Long masterClasstId) {
    this.masterClasstId = masterClasstId;
  }

  public MasterStudyClassDTO masterSubjectId(Long masterSubjectId) {
    this.masterSubjectId = masterSubjectId;
    return this;
  }

   /**
   * Get masterSubjectId
   * @return masterSubjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMasterSubjectId() {
    return masterSubjectId;
  }

  public void setMasterSubjectId(Long masterSubjectId) {
    this.masterSubjectId = masterSubjectId;
  }

  public MasterStudyClassDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MasterStudyClassDTO seqNo(Long seqNo) {
    this.seqNo = seqNo;
    return this;
  }

   /**
   * Get seqNo
   * @return seqNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSeqNo() {
    return seqNo;
  }

  public void setSeqNo(Long seqNo) {
    this.seqNo = seqNo;
  }

  public MasterStudyClassDTO userBased(Boolean userBased) {
    this.userBased = userBased;
    return this;
  }

   /**
   * Get userBased
   * @return userBased
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUserBased() {
    return userBased;
  }

  public void setUserBased(Boolean userBased) {
    this.userBased = userBased;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MasterStudyClassDTO masterStudyClassDTO = (MasterStudyClassDTO) o;
    return Objects.equals(this.id, masterStudyClassDTO.id) &&
        Objects.equals(this.masterClasstId, masterStudyClassDTO.masterClasstId) &&
        Objects.equals(this.masterSubjectId, masterStudyClassDTO.masterSubjectId) &&
        Objects.equals(this.name, masterStudyClassDTO.name) &&
        Objects.equals(this.seqNo, masterStudyClassDTO.seqNo) &&
        Objects.equals(this.userBased, masterStudyClassDTO.userBased);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, masterClasstId, masterSubjectId, name, seqNo, userBased);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MasterStudyClassDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    masterClasstId: ").append(toIndentedString(masterClasstId)).append("\n");
    sb.append("    masterSubjectId: ").append(toIndentedString(masterSubjectId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    seqNo: ").append(toIndentedString(seqNo)).append("\n");
    sb.append("    userBased: ").append(toIndentedString(userBased)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

