/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * MGSContentResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class MGSContentResponse   {
  @SerializedName("activityContent")
  private Boolean activityContent = null;

  @SerializedName("activityTypeContent")
  private Boolean activityTypeContent = null;

  @SerializedName("baseSubjectId")
  private Long baseSubjectId = null;

  @SerializedName("contentInfoId")
  private Long contentInfoId = null;

  @SerializedName("contentRootPath")
  private String contentRootPath = null;

  @SerializedName("contentType")
  private String contentType = null;

  @SerializedName("encryptSign")
  private String encryptSign = null;

  @SerializedName("fileContent")
  private String fileContent = null;

  @SerializedName("filePath")
  private String filePath = null;

  @SerializedName("fileType")
  private String fileType = null;

  @SerializedName("fileTypeOrdinal")
  private Long fileTypeOrdinal = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("languageName")
  private String languageName = null;

  @SerializedName("lastUploadDate")
  private DateTime lastUploadDate = null;

  @SerializedName("mathsLab")
  private Boolean mathsLab = null;

  @SerializedName("md5Sign")
  private String md5Sign = null;

  @SerializedName("metaInfo")
  private String metaInfo = null;

  @SerializedName("moduleType")
  private Integer moduleType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pageNo")
  private String pageNo = null;

  @SerializedName("peerId")
  private Long peerId = null;

  @SerializedName("published")
  private Boolean published = null;

  @SerializedName("publishedDate")
  private DateTime publishedDate = null;

  @SerializedName("scriptBased")
  private Boolean scriptBased = null;

  @SerializedName("sectionName")
  private String sectionName = null;

  @SerializedName("sectionType")
  private String sectionType = null;

  @SerializedName("seq")
  private Long seq = null;

  @SerializedName("svnPath")
  private String svnPath = null;

  @SerializedName("svnRevisionNumber")
  private Long svnRevisionNumber = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("title")
  private String title = null;

  public MGSContentResponse activityContent(Boolean activityContent) {
    this.activityContent = activityContent;
    return this;
  }

   /**
   * Get activityContent
   * @return activityContent
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getActivityContent() {
    return activityContent;
  }

  public void setActivityContent(Boolean activityContent) {
    this.activityContent = activityContent;
  }

  public MGSContentResponse activityTypeContent(Boolean activityTypeContent) {
    this.activityTypeContent = activityTypeContent;
    return this;
  }

   /**
   * Get activityTypeContent
   * @return activityTypeContent
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getActivityTypeContent() {
    return activityTypeContent;
  }

  public void setActivityTypeContent(Boolean activityTypeContent) {
    this.activityTypeContent = activityTypeContent;
  }

  public MGSContentResponse baseSubjectId(Long baseSubjectId) {
    this.baseSubjectId = baseSubjectId;
    return this;
  }

   /**
   * Get baseSubjectId
   * @return baseSubjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBaseSubjectId() {
    return baseSubjectId;
  }

  public void setBaseSubjectId(Long baseSubjectId) {
    this.baseSubjectId = baseSubjectId;
  }

  public MGSContentResponse contentInfoId(Long contentInfoId) {
    this.contentInfoId = contentInfoId;
    return this;
  }

   /**
   * Get contentInfoId
   * @return contentInfoId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getContentInfoId() {
    return contentInfoId;
  }

  public void setContentInfoId(Long contentInfoId) {
    this.contentInfoId = contentInfoId;
  }

  public MGSContentResponse contentRootPath(String contentRootPath) {
    this.contentRootPath = contentRootPath;
    return this;
  }

   /**
   * Get contentRootPath
   * @return contentRootPath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContentRootPath() {
    return contentRootPath;
  }

  public void setContentRootPath(String contentRootPath) {
    this.contentRootPath = contentRootPath;
  }

  public MGSContentResponse contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public MGSContentResponse encryptSign(String encryptSign) {
    this.encryptSign = encryptSign;
    return this;
  }

   /**
   * Get encryptSign
   * @return encryptSign
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEncryptSign() {
    return encryptSign;
  }

  public void setEncryptSign(String encryptSign) {
    this.encryptSign = encryptSign;
  }

  public MGSContentResponse fileContent(String fileContent) {
    this.fileContent = fileContent;
    return this;
  }

   /**
   * Get fileContent
   * @return fileContent
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFileContent() {
    return fileContent;
  }

  public void setFileContent(String fileContent) {
    this.fileContent = fileContent;
  }

  public MGSContentResponse filePath(String filePath) {
    this.filePath = filePath;
    return this;
  }

   /**
   * Get filePath
   * @return filePath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFilePath() {
    return filePath;
  }

  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }

  public MGSContentResponse fileType(String fileType) {
    this.fileType = fileType;
    return this;
  }

   /**
   * Get fileType
   * @return fileType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFileType() {
    return fileType;
  }

  public void setFileType(String fileType) {
    this.fileType = fileType;
  }

  public MGSContentResponse fileTypeOrdinal(Long fileTypeOrdinal) {
    this.fileTypeOrdinal = fileTypeOrdinal;
    return this;
  }

   /**
   * Get fileTypeOrdinal
   * @return fileTypeOrdinal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getFileTypeOrdinal() {
    return fileTypeOrdinal;
  }

  public void setFileTypeOrdinal(Long fileTypeOrdinal) {
    this.fileTypeOrdinal = fileTypeOrdinal;
  }

  public MGSContentResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public MGSContentResponse label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public MGSContentResponse languageName(String languageName) {
    this.languageName = languageName;
    return this;
  }

   /**
   * Get languageName
   * @return languageName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLanguageName() {
    return languageName;
  }

  public void setLanguageName(String languageName) {
    this.languageName = languageName;
  }

  public MGSContentResponse lastUploadDate(DateTime lastUploadDate) {
    this.lastUploadDate = lastUploadDate;
    return this;
  }

   /**
   * Get lastUploadDate
   * @return lastUploadDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLastUploadDate() {
    return lastUploadDate;
  }

  public void setLastUploadDate(DateTime lastUploadDate) {
    this.lastUploadDate = lastUploadDate;
  }

  public MGSContentResponse mathsLab(Boolean mathsLab) {
    this.mathsLab = mathsLab;
    return this;
  }

   /**
   * Get mathsLab
   * @return mathsLab
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMathsLab() {
    return mathsLab;
  }

  public void setMathsLab(Boolean mathsLab) {
    this.mathsLab = mathsLab;
  }

  public MGSContentResponse md5Sign(String md5Sign) {
    this.md5Sign = md5Sign;
    return this;
  }

   /**
   * Get md5Sign
   * @return md5Sign
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMd5Sign() {
    return md5Sign;
  }

  public void setMd5Sign(String md5Sign) {
    this.md5Sign = md5Sign;
  }

  public MGSContentResponse metaInfo(String metaInfo) {
    this.metaInfo = metaInfo;
    return this;
  }

   /**
   * Get metaInfo
   * @return metaInfo
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMetaInfo() {
    return metaInfo;
  }

  public void setMetaInfo(String metaInfo) {
    this.metaInfo = metaInfo;
  }

  public MGSContentResponse moduleType(Integer moduleType) {
    this.moduleType = moduleType;
    return this;
  }

   /**
   * Get moduleType
   * @return moduleType
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getModuleType() {
    return moduleType;
  }

  public void setModuleType(Integer moduleType) {
    this.moduleType = moduleType;
  }

  public MGSContentResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MGSContentResponse pageNo(String pageNo) {
    this.pageNo = pageNo;
    return this;
  }

   /**
   * Get pageNo
   * @return pageNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPageNo() {
    return pageNo;
  }

  public void setPageNo(String pageNo) {
    this.pageNo = pageNo;
  }

  public MGSContentResponse peerId(Long peerId) {
    this.peerId = peerId;
    return this;
  }

   /**
   * Get peerId
   * @return peerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPeerId() {
    return peerId;
  }

  public void setPeerId(Long peerId) {
    this.peerId = peerId;
  }

  public MGSContentResponse published(Boolean published) {
    this.published = published;
    return this;
  }

   /**
   * Get published
   * @return published
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getPublished() {
    return published;
  }

  public void setPublished(Boolean published) {
    this.published = published;
  }

  public MGSContentResponse publishedDate(DateTime publishedDate) {
    this.publishedDate = publishedDate;
    return this;
  }

   /**
   * Get publishedDate
   * @return publishedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getPublishedDate() {
    return publishedDate;
  }

  public void setPublishedDate(DateTime publishedDate) {
    this.publishedDate = publishedDate;
  }

  public MGSContentResponse scriptBased(Boolean scriptBased) {
    this.scriptBased = scriptBased;
    return this;
  }

   /**
   * Get scriptBased
   * @return scriptBased
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getScriptBased() {
    return scriptBased;
  }

  public void setScriptBased(Boolean scriptBased) {
    this.scriptBased = scriptBased;
  }

  public MGSContentResponse sectionName(String sectionName) {
    this.sectionName = sectionName;
    return this;
  }

   /**
   * Get sectionName
   * @return sectionName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSectionName() {
    return sectionName;
  }

  public void setSectionName(String sectionName) {
    this.sectionName = sectionName;
  }

  public MGSContentResponse sectionType(String sectionType) {
    this.sectionType = sectionType;
    return this;
  }

   /**
   * Get sectionType
   * @return sectionType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSectionType() {
    return sectionType;
  }

  public void setSectionType(String sectionType) {
    this.sectionType = sectionType;
  }

  public MGSContentResponse seq(Long seq) {
    this.seq = seq;
    return this;
  }

   /**
   * Get seq
   * @return seq
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSeq() {
    return seq;
  }

  public void setSeq(Long seq) {
    this.seq = seq;
  }

  public MGSContentResponse svnPath(String svnPath) {
    this.svnPath = svnPath;
    return this;
  }

   /**
   * Get svnPath
   * @return svnPath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSvnPath() {
    return svnPath;
  }

  public void setSvnPath(String svnPath) {
    this.svnPath = svnPath;
  }

  public MGSContentResponse svnRevisionNumber(Long svnRevisionNumber) {
    this.svnRevisionNumber = svnRevisionNumber;
    return this;
  }

   /**
   * Get svnRevisionNumber
   * @return svnRevisionNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSvnRevisionNumber() {
    return svnRevisionNumber;
  }

  public void setSvnRevisionNumber(Long svnRevisionNumber) {
    this.svnRevisionNumber = svnRevisionNumber;
  }

  public MGSContentResponse tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public MGSContentResponse title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MGSContentResponse mGSContentResponse = (MGSContentResponse) o;
    return Objects.equals(this.activityContent, mGSContentResponse.activityContent) &&
        Objects.equals(this.activityTypeContent, mGSContentResponse.activityTypeContent) &&
        Objects.equals(this.baseSubjectId, mGSContentResponse.baseSubjectId) &&
        Objects.equals(this.contentInfoId, mGSContentResponse.contentInfoId) &&
        Objects.equals(this.contentRootPath, mGSContentResponse.contentRootPath) &&
        Objects.equals(this.contentType, mGSContentResponse.contentType) &&
        Objects.equals(this.encryptSign, mGSContentResponse.encryptSign) &&
        Objects.equals(this.fileContent, mGSContentResponse.fileContent) &&
        Objects.equals(this.filePath, mGSContentResponse.filePath) &&
        Objects.equals(this.fileType, mGSContentResponse.fileType) &&
        Objects.equals(this.fileTypeOrdinal, mGSContentResponse.fileTypeOrdinal) &&
        Objects.equals(this.id, mGSContentResponse.id) &&
        Objects.equals(this.label, mGSContentResponse.label) &&
        Objects.equals(this.languageName, mGSContentResponse.languageName) &&
        Objects.equals(this.lastUploadDate, mGSContentResponse.lastUploadDate) &&
        Objects.equals(this.mathsLab, mGSContentResponse.mathsLab) &&
        Objects.equals(this.md5Sign, mGSContentResponse.md5Sign) &&
        Objects.equals(this.metaInfo, mGSContentResponse.metaInfo) &&
        Objects.equals(this.moduleType, mGSContentResponse.moduleType) &&
        Objects.equals(this.name, mGSContentResponse.name) &&
        Objects.equals(this.pageNo, mGSContentResponse.pageNo) &&
        Objects.equals(this.peerId, mGSContentResponse.peerId) &&
        Objects.equals(this.published, mGSContentResponse.published) &&
        Objects.equals(this.publishedDate, mGSContentResponse.publishedDate) &&
        Objects.equals(this.scriptBased, mGSContentResponse.scriptBased) &&
        Objects.equals(this.sectionName, mGSContentResponse.sectionName) &&
        Objects.equals(this.sectionType, mGSContentResponse.sectionType) &&
        Objects.equals(this.seq, mGSContentResponse.seq) &&
        Objects.equals(this.svnPath, mGSContentResponse.svnPath) &&
        Objects.equals(this.svnRevisionNumber, mGSContentResponse.svnRevisionNumber) &&
        Objects.equals(this.tags, mGSContentResponse.tags) &&
        Objects.equals(this.title, mGSContentResponse.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activityContent, activityTypeContent, baseSubjectId, contentInfoId, contentRootPath, contentType, encryptSign, fileContent, filePath, fileType, fileTypeOrdinal, id, label, languageName, lastUploadDate, mathsLab, md5Sign, metaInfo, moduleType, name, pageNo, peerId, published, publishedDate, scriptBased, sectionName, sectionType, seq, svnPath, svnRevisionNumber, tags, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MGSContentResponse {\n");
    
    sb.append("    activityContent: ").append(toIndentedString(activityContent)).append("\n");
    sb.append("    activityTypeContent: ").append(toIndentedString(activityTypeContent)).append("\n");
    sb.append("    baseSubjectId: ").append(toIndentedString(baseSubjectId)).append("\n");
    sb.append("    contentInfoId: ").append(toIndentedString(contentInfoId)).append("\n");
    sb.append("    contentRootPath: ").append(toIndentedString(contentRootPath)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    encryptSign: ").append(toIndentedString(encryptSign)).append("\n");
    sb.append("    fileContent: ").append(toIndentedString(fileContent)).append("\n");
    sb.append("    filePath: ").append(toIndentedString(filePath)).append("\n");
    sb.append("    fileType: ").append(toIndentedString(fileType)).append("\n");
    sb.append("    fileTypeOrdinal: ").append(toIndentedString(fileTypeOrdinal)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    languageName: ").append(toIndentedString(languageName)).append("\n");
    sb.append("    lastUploadDate: ").append(toIndentedString(lastUploadDate)).append("\n");
    sb.append("    mathsLab: ").append(toIndentedString(mathsLab)).append("\n");
    sb.append("    md5Sign: ").append(toIndentedString(md5Sign)).append("\n");
    sb.append("    metaInfo: ").append(toIndentedString(metaInfo)).append("\n");
    sb.append("    moduleType: ").append(toIndentedString(moduleType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pageNo: ").append(toIndentedString(pageNo)).append("\n");
    sb.append("    peerId: ").append(toIndentedString(peerId)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    publishedDate: ").append(toIndentedString(publishedDate)).append("\n");
    sb.append("    scriptBased: ").append(toIndentedString(scriptBased)).append("\n");
    sb.append("    sectionName: ").append(toIndentedString(sectionName)).append("\n");
    sb.append("    sectionType: ").append(toIndentedString(sectionType)).append("\n");
    sb.append("    seq: ").append(toIndentedString(seq)).append("\n");
    sb.append("    svnPath: ").append(toIndentedString(svnPath)).append("\n");
    sb.append("    svnRevisionNumber: ").append(toIndentedString(svnRevisionNumber)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

