/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.LectureResourceResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * PlanResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class PlanResponse   {
  @SerializedName("chapterName")
  private String chapterName = null;

  @SerializedName("className")
  private String className = null;

  @SerializedName("date")
  private DateTime date = null;

  @SerializedName("dateStr")
  private String dateStr = null;

  @SerializedName("discussionTime")
  private Integer discussionTime = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("endTime")
  private String endTime = null;

  @SerializedName("explanationTime")
  private Integer explanationTime = null;

  @SerializedName("learningPlanId")
  private Long learningPlanId = null;

  @SerializedName("learningPlanMemberId")
  private Long learningPlanMemberId = null;

  @SerializedName("learningPlanMemberUuid")
  private String learningPlanMemberUuid = null;

  @SerializedName("learningPlanUuid")
  private String learningPlanUuid = null;

  @SerializedName("lectureResources")
  private List<LectureResourceResponse> lectureResources = new ArrayList<LectureResourceResponse>();

  @SerializedName("location")
  private String location = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("objective")
  private String objective = null;

  @SerializedName("planNo")
  private Long planNo = null;

  @SerializedName("planTypeId")
  private Long planTypeId = null;

  @SerializedName("planTypeUuid")
  private String planTypeUuid = null;

  @SerializedName("scheduled")
  private Boolean scheduled = null;

  @SerializedName("sectionId")
  private Long sectionId = null;

  @SerializedName("sectionName")
  private String sectionName = null;

  @SerializedName("startTime")
  private String startTime = null;

  @SerializedName("subjectName")
  private String subjectName = null;

  @SerializedName("totalAVDuartion")
  private Integer totalAVDuartion = null;

  @SerializedName("totalActivitiesDuartion")
  private Integer totalActivitiesDuartion = null;

  @SerializedName("totalAssessmentDuartion")
  private Integer totalAssessmentDuartion = null;

  @SerializedName("totalDocumentsDuartion")
  private Integer totalDocumentsDuartion = null;

  @SerializedName("totalOtherDuartion")
  private Integer totalOtherDuartion = null;

  @SerializedName("totalResourceDuartion")
  private Integer totalResourceDuartion = null;

  public PlanResponse chapterName(String chapterName) {
    this.chapterName = chapterName;
    return this;
  }

   /**
   * Get chapterName
   * @return chapterName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChapterName() {
    return chapterName;
  }

  public void setChapterName(String chapterName) {
    this.chapterName = chapterName;
  }

  public PlanResponse className(String className) {
    this.className = className;
    return this;
  }

   /**
   * Get className
   * @return className
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }

  public PlanResponse date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public PlanResponse dateStr(String dateStr) {
    this.dateStr = dateStr;
    return this;
  }

   /**
   * Get dateStr
   * @return dateStr
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDateStr() {
    return dateStr;
  }

  public void setDateStr(String dateStr) {
    this.dateStr = dateStr;
  }

  public PlanResponse discussionTime(Integer discussionTime) {
    this.discussionTime = discussionTime;
    return this;
  }

   /**
   * Get discussionTime
   * @return discussionTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDiscussionTime() {
    return discussionTime;
  }

  public void setDiscussionTime(Integer discussionTime) {
    this.discussionTime = discussionTime;
  }

  public PlanResponse duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public PlanResponse endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public PlanResponse explanationTime(Integer explanationTime) {
    this.explanationTime = explanationTime;
    return this;
  }

   /**
   * Get explanationTime
   * @return explanationTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getExplanationTime() {
    return explanationTime;
  }

  public void setExplanationTime(Integer explanationTime) {
    this.explanationTime = explanationTime;
  }

  public PlanResponse learningPlanId(Long learningPlanId) {
    this.learningPlanId = learningPlanId;
    return this;
  }

   /**
   * Get learningPlanId
   * @return learningPlanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLearningPlanId() {
    return learningPlanId;
  }

  public void setLearningPlanId(Long learningPlanId) {
    this.learningPlanId = learningPlanId;
  }

  public PlanResponse learningPlanMemberId(Long learningPlanMemberId) {
    this.learningPlanMemberId = learningPlanMemberId;
    return this;
  }

   /**
   * Get learningPlanMemberId
   * @return learningPlanMemberId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLearningPlanMemberId() {
    return learningPlanMemberId;
  }

  public void setLearningPlanMemberId(Long learningPlanMemberId) {
    this.learningPlanMemberId = learningPlanMemberId;
  }

  public PlanResponse learningPlanMemberUuid(String learningPlanMemberUuid) {
    this.learningPlanMemberUuid = learningPlanMemberUuid;
    return this;
  }

   /**
   * Get learningPlanMemberUuid
   * @return learningPlanMemberUuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLearningPlanMemberUuid() {
    return learningPlanMemberUuid;
  }

  public void setLearningPlanMemberUuid(String learningPlanMemberUuid) {
    this.learningPlanMemberUuid = learningPlanMemberUuid;
  }

  public PlanResponse learningPlanUuid(String learningPlanUuid) {
    this.learningPlanUuid = learningPlanUuid;
    return this;
  }

   /**
   * Get learningPlanUuid
   * @return learningPlanUuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLearningPlanUuid() {
    return learningPlanUuid;
  }

  public void setLearningPlanUuid(String learningPlanUuid) {
    this.learningPlanUuid = learningPlanUuid;
  }

  public PlanResponse lectureResources(List<LectureResourceResponse> lectureResources) {
    this.lectureResources = lectureResources;
    return this;
  }

  public PlanResponse addLectureResourcesItem(LectureResourceResponse lectureResourcesItem) {
    this.lectureResources.add(lectureResourcesItem);
    return this;
  }

   /**
   * Get lectureResources
   * @return lectureResources
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LectureResourceResponse> getLectureResources() {
    return lectureResources;
  }

  public void setLectureResources(List<LectureResourceResponse> lectureResources) {
    this.lectureResources = lectureResources;
  }

  public PlanResponse location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public PlanResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PlanResponse objective(String objective) {
    this.objective = objective;
    return this;
  }

   /**
   * Get objective
   * @return objective
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObjective() {
    return objective;
  }

  public void setObjective(String objective) {
    this.objective = objective;
  }

  public PlanResponse planNo(Long planNo) {
    this.planNo = planNo;
    return this;
  }

   /**
   * Get planNo
   * @return planNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPlanNo() {
    return planNo;
  }

  public void setPlanNo(Long planNo) {
    this.planNo = planNo;
  }

  public PlanResponse planTypeId(Long planTypeId) {
    this.planTypeId = planTypeId;
    return this;
  }

   /**
   * Get planTypeId
   * @return planTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPlanTypeId() {
    return planTypeId;
  }

  public void setPlanTypeId(Long planTypeId) {
    this.planTypeId = planTypeId;
  }

  public PlanResponse planTypeUuid(String planTypeUuid) {
    this.planTypeUuid = planTypeUuid;
    return this;
  }

   /**
   * Get planTypeUuid
   * @return planTypeUuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlanTypeUuid() {
    return planTypeUuid;
  }

  public void setPlanTypeUuid(String planTypeUuid) {
    this.planTypeUuid = planTypeUuid;
  }

  public PlanResponse scheduled(Boolean scheduled) {
    this.scheduled = scheduled;
    return this;
  }

   /**
   * Get scheduled
   * @return scheduled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getScheduled() {
    return scheduled;
  }

  public void setScheduled(Boolean scheduled) {
    this.scheduled = scheduled;
  }

  public PlanResponse sectionId(Long sectionId) {
    this.sectionId = sectionId;
    return this;
  }

   /**
   * Get sectionId
   * @return sectionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSectionId() {
    return sectionId;
  }

  public void setSectionId(Long sectionId) {
    this.sectionId = sectionId;
  }

  public PlanResponse sectionName(String sectionName) {
    this.sectionName = sectionName;
    return this;
  }

   /**
   * Get sectionName
   * @return sectionName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSectionName() {
    return sectionName;
  }

  public void setSectionName(String sectionName) {
    this.sectionName = sectionName;
  }

  public PlanResponse startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public PlanResponse subjectName(String subjectName) {
    this.subjectName = subjectName;
    return this;
  }

   /**
   * Get subjectName
   * @return subjectName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubjectName() {
    return subjectName;
  }

  public void setSubjectName(String subjectName) {
    this.subjectName = subjectName;
  }

  public PlanResponse totalAVDuartion(Integer totalAVDuartion) {
    this.totalAVDuartion = totalAVDuartion;
    return this;
  }

   /**
   * Get totalAVDuartion
   * @return totalAVDuartion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalAVDuartion() {
    return totalAVDuartion;
  }

  public void setTotalAVDuartion(Integer totalAVDuartion) {
    this.totalAVDuartion = totalAVDuartion;
  }

  public PlanResponse totalActivitiesDuartion(Integer totalActivitiesDuartion) {
    this.totalActivitiesDuartion = totalActivitiesDuartion;
    return this;
  }

   /**
   * Get totalActivitiesDuartion
   * @return totalActivitiesDuartion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalActivitiesDuartion() {
    return totalActivitiesDuartion;
  }

  public void setTotalActivitiesDuartion(Integer totalActivitiesDuartion) {
    this.totalActivitiesDuartion = totalActivitiesDuartion;
  }

  public PlanResponse totalAssessmentDuartion(Integer totalAssessmentDuartion) {
    this.totalAssessmentDuartion = totalAssessmentDuartion;
    return this;
  }

   /**
   * Get totalAssessmentDuartion
   * @return totalAssessmentDuartion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalAssessmentDuartion() {
    return totalAssessmentDuartion;
  }

  public void setTotalAssessmentDuartion(Integer totalAssessmentDuartion) {
    this.totalAssessmentDuartion = totalAssessmentDuartion;
  }

  public PlanResponse totalDocumentsDuartion(Integer totalDocumentsDuartion) {
    this.totalDocumentsDuartion = totalDocumentsDuartion;
    return this;
  }

   /**
   * Get totalDocumentsDuartion
   * @return totalDocumentsDuartion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalDocumentsDuartion() {
    return totalDocumentsDuartion;
  }

  public void setTotalDocumentsDuartion(Integer totalDocumentsDuartion) {
    this.totalDocumentsDuartion = totalDocumentsDuartion;
  }

  public PlanResponse totalOtherDuartion(Integer totalOtherDuartion) {
    this.totalOtherDuartion = totalOtherDuartion;
    return this;
  }

   /**
   * Get totalOtherDuartion
   * @return totalOtherDuartion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalOtherDuartion() {
    return totalOtherDuartion;
  }

  public void setTotalOtherDuartion(Integer totalOtherDuartion) {
    this.totalOtherDuartion = totalOtherDuartion;
  }

  public PlanResponse totalResourceDuartion(Integer totalResourceDuartion) {
    this.totalResourceDuartion = totalResourceDuartion;
    return this;
  }

   /**
   * Get totalResourceDuartion
   * @return totalResourceDuartion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalResourceDuartion() {
    return totalResourceDuartion;
  }

  public void setTotalResourceDuartion(Integer totalResourceDuartion) {
    this.totalResourceDuartion = totalResourceDuartion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanResponse planResponse = (PlanResponse) o;
    return Objects.equals(this.chapterName, planResponse.chapterName) &&
        Objects.equals(this.className, planResponse.className) &&
        Objects.equals(this.date, planResponse.date) &&
        Objects.equals(this.dateStr, planResponse.dateStr) &&
        Objects.equals(this.discussionTime, planResponse.discussionTime) &&
        Objects.equals(this.duration, planResponse.duration) &&
        Objects.equals(this.endTime, planResponse.endTime) &&
        Objects.equals(this.explanationTime, planResponse.explanationTime) &&
        Objects.equals(this.learningPlanId, planResponse.learningPlanId) &&
        Objects.equals(this.learningPlanMemberId, planResponse.learningPlanMemberId) &&
        Objects.equals(this.learningPlanMemberUuid, planResponse.learningPlanMemberUuid) &&
        Objects.equals(this.learningPlanUuid, planResponse.learningPlanUuid) &&
        Objects.equals(this.lectureResources, planResponse.lectureResources) &&
        Objects.equals(this.location, planResponse.location) &&
        Objects.equals(this.name, planResponse.name) &&
        Objects.equals(this.objective, planResponse.objective) &&
        Objects.equals(this.planNo, planResponse.planNo) &&
        Objects.equals(this.planTypeId, planResponse.planTypeId) &&
        Objects.equals(this.planTypeUuid, planResponse.planTypeUuid) &&
        Objects.equals(this.scheduled, planResponse.scheduled) &&
        Objects.equals(this.sectionId, planResponse.sectionId) &&
        Objects.equals(this.sectionName, planResponse.sectionName) &&
        Objects.equals(this.startTime, planResponse.startTime) &&
        Objects.equals(this.subjectName, planResponse.subjectName) &&
        Objects.equals(this.totalAVDuartion, planResponse.totalAVDuartion) &&
        Objects.equals(this.totalActivitiesDuartion, planResponse.totalActivitiesDuartion) &&
        Objects.equals(this.totalAssessmentDuartion, planResponse.totalAssessmentDuartion) &&
        Objects.equals(this.totalDocumentsDuartion, planResponse.totalDocumentsDuartion) &&
        Objects.equals(this.totalOtherDuartion, planResponse.totalOtherDuartion) &&
        Objects.equals(this.totalResourceDuartion, planResponse.totalResourceDuartion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chapterName, className, date, dateStr, discussionTime, duration, endTime, explanationTime, learningPlanId, learningPlanMemberId, learningPlanMemberUuid, learningPlanUuid, lectureResources, location, name, objective, planNo, planTypeId, planTypeUuid, scheduled, sectionId, sectionName, startTime, subjectName, totalAVDuartion, totalActivitiesDuartion, totalAssessmentDuartion, totalDocumentsDuartion, totalOtherDuartion, totalResourceDuartion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanResponse {\n");
    
    sb.append("    chapterName: ").append(toIndentedString(chapterName)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dateStr: ").append(toIndentedString(dateStr)).append("\n");
    sb.append("    discussionTime: ").append(toIndentedString(discussionTime)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    explanationTime: ").append(toIndentedString(explanationTime)).append("\n");
    sb.append("    learningPlanId: ").append(toIndentedString(learningPlanId)).append("\n");
    sb.append("    learningPlanMemberId: ").append(toIndentedString(learningPlanMemberId)).append("\n");
    sb.append("    learningPlanMemberUuid: ").append(toIndentedString(learningPlanMemberUuid)).append("\n");
    sb.append("    learningPlanUuid: ").append(toIndentedString(learningPlanUuid)).append("\n");
    sb.append("    lectureResources: ").append(toIndentedString(lectureResources)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    objective: ").append(toIndentedString(objective)).append("\n");
    sb.append("    planNo: ").append(toIndentedString(planNo)).append("\n");
    sb.append("    planTypeId: ").append(toIndentedString(planTypeId)).append("\n");
    sb.append("    planTypeUuid: ").append(toIndentedString(planTypeUuid)).append("\n");
    sb.append("    scheduled: ").append(toIndentedString(scheduled)).append("\n");
    sb.append("    sectionId: ").append(toIndentedString(sectionId)).append("\n");
    sb.append("    sectionName: ").append(toIndentedString(sectionName)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    subjectName: ").append(toIndentedString(subjectName)).append("\n");
    sb.append("    totalAVDuartion: ").append(toIndentedString(totalAVDuartion)).append("\n");
    sb.append("    totalActivitiesDuartion: ").append(toIndentedString(totalActivitiesDuartion)).append("\n");
    sb.append("    totalAssessmentDuartion: ").append(toIndentedString(totalAssessmentDuartion)).append("\n");
    sb.append("    totalDocumentsDuartion: ").append(toIndentedString(totalDocumentsDuartion)).append("\n");
    sb.append("    totalOtherDuartion: ").append(toIndentedString(totalOtherDuartion)).append("\n");
    sb.append("    totalResourceDuartion: ").append(toIndentedString(totalResourceDuartion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

