/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.AssessmentQuestionShortResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * RuleQuestionsRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class RuleQuestionsRequest   {
  @SerializedName("noOfQuestions")
  private Long noOfQuestions = null;

  @SerializedName("noOfQuestionsSelected")
  private Long noOfQuestionsSelected = null;

  @SerializedName("questions")
  private List<AssessmentQuestionShortResponse> questions = new ArrayList<AssessmentQuestionShortResponse>();

  @SerializedName("questionsRequired")
  private Boolean questionsRequired = null;

  @SerializedName("ruleNameKey")
  private String ruleNameKey = null;

  @SerializedName("ruleNameParams")
  private List<String> ruleNameParams = new ArrayList<String>();

  @SerializedName("selectedQuestions")
  private List<AssessmentQuestionShortResponse> selectedQuestions = new ArrayList<AssessmentQuestionShortResponse>();

  public RuleQuestionsRequest noOfQuestions(Long noOfQuestions) {
    this.noOfQuestions = noOfQuestions;
    return this;
  }

   /**
   * Get noOfQuestions
   * @return noOfQuestions
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNoOfQuestions() {
    return noOfQuestions;
  }

  public void setNoOfQuestions(Long noOfQuestions) {
    this.noOfQuestions = noOfQuestions;
  }

  public RuleQuestionsRequest noOfQuestionsSelected(Long noOfQuestionsSelected) {
    this.noOfQuestionsSelected = noOfQuestionsSelected;
    return this;
  }

   /**
   * Get noOfQuestionsSelected
   * @return noOfQuestionsSelected
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNoOfQuestionsSelected() {
    return noOfQuestionsSelected;
  }

  public void setNoOfQuestionsSelected(Long noOfQuestionsSelected) {
    this.noOfQuestionsSelected = noOfQuestionsSelected;
  }

  public RuleQuestionsRequest questions(List<AssessmentQuestionShortResponse> questions) {
    this.questions = questions;
    return this;
  }

  public RuleQuestionsRequest addQuestionsItem(AssessmentQuestionShortResponse questionsItem) {
    this.questions.add(questionsItem);
    return this;
  }

   /**
   * Get questions
   * @return questions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AssessmentQuestionShortResponse> getQuestions() {
    return questions;
  }

  public void setQuestions(List<AssessmentQuestionShortResponse> questions) {
    this.questions = questions;
  }

  public RuleQuestionsRequest questionsRequired(Boolean questionsRequired) {
    this.questionsRequired = questionsRequired;
    return this;
  }

   /**
   * Get questionsRequired
   * @return questionsRequired
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getQuestionsRequired() {
    return questionsRequired;
  }

  public void setQuestionsRequired(Boolean questionsRequired) {
    this.questionsRequired = questionsRequired;
  }

  public RuleQuestionsRequest ruleNameKey(String ruleNameKey) {
    this.ruleNameKey = ruleNameKey;
    return this;
  }

   /**
   * Get ruleNameKey
   * @return ruleNameKey
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRuleNameKey() {
    return ruleNameKey;
  }

  public void setRuleNameKey(String ruleNameKey) {
    this.ruleNameKey = ruleNameKey;
  }

  public RuleQuestionsRequest ruleNameParams(List<String> ruleNameParams) {
    this.ruleNameParams = ruleNameParams;
    return this;
  }

  public RuleQuestionsRequest addRuleNameParamsItem(String ruleNameParamsItem) {
    this.ruleNameParams.add(ruleNameParamsItem);
    return this;
  }

   /**
   * Get ruleNameParams
   * @return ruleNameParams
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getRuleNameParams() {
    return ruleNameParams;
  }

  public void setRuleNameParams(List<String> ruleNameParams) {
    this.ruleNameParams = ruleNameParams;
  }

  public RuleQuestionsRequest selectedQuestions(List<AssessmentQuestionShortResponse> selectedQuestions) {
    this.selectedQuestions = selectedQuestions;
    return this;
  }

  public RuleQuestionsRequest addSelectedQuestionsItem(AssessmentQuestionShortResponse selectedQuestionsItem) {
    this.selectedQuestions.add(selectedQuestionsItem);
    return this;
  }

   /**
   * Get selectedQuestions
   * @return selectedQuestions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AssessmentQuestionShortResponse> getSelectedQuestions() {
    return selectedQuestions;
  }

  public void setSelectedQuestions(List<AssessmentQuestionShortResponse> selectedQuestions) {
    this.selectedQuestions = selectedQuestions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleQuestionsRequest ruleQuestionsRequest = (RuleQuestionsRequest) o;
    return Objects.equals(this.noOfQuestions, ruleQuestionsRequest.noOfQuestions) &&
        Objects.equals(this.noOfQuestionsSelected, ruleQuestionsRequest.noOfQuestionsSelected) &&
        Objects.equals(this.questions, ruleQuestionsRequest.questions) &&
        Objects.equals(this.questionsRequired, ruleQuestionsRequest.questionsRequired) &&
        Objects.equals(this.ruleNameKey, ruleQuestionsRequest.ruleNameKey) &&
        Objects.equals(this.ruleNameParams, ruleQuestionsRequest.ruleNameParams) &&
        Objects.equals(this.selectedQuestions, ruleQuestionsRequest.selectedQuestions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(noOfQuestions, noOfQuestionsSelected, questions, questionsRequired, ruleNameKey, ruleNameParams, selectedQuestions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleQuestionsRequest {\n");
    
    sb.append("    noOfQuestions: ").append(toIndentedString(noOfQuestions)).append("\n");
    sb.append("    noOfQuestionsSelected: ").append(toIndentedString(noOfQuestionsSelected)).append("\n");
    sb.append("    questions: ").append(toIndentedString(questions)).append("\n");
    sb.append("    questionsRequired: ").append(toIndentedString(questionsRequired)).append("\n");
    sb.append("    ruleNameKey: ").append(toIndentedString(ruleNameKey)).append("\n");
    sb.append("    ruleNameParams: ").append(toIndentedString(ruleNameParams)).append("\n");
    sb.append("    selectedQuestions: ").append(toIndentedString(selectedQuestions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

