/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SegmentRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class SegmentRequest   {
  @SerializedName("addKeyWords")
  private String addKeyWords = null;

  @SerializedName("frame")
  private Integer frame = null;

  @SerializedName("length")
  private Integer length = null;

  @SerializedName("sceneName")
  private String sceneName = null;

  @SerializedName("tenantId")
  private Long tenantId = null;

  @SerializedName("textContent")
  private String textContent = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("uuid")
  private String uuid = null;

  public SegmentRequest addKeyWords(String addKeyWords) {
    this.addKeyWords = addKeyWords;
    return this;
  }

   /**
   * Get addKeyWords
   * @return addKeyWords
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddKeyWords() {
    return addKeyWords;
  }

  public void setAddKeyWords(String addKeyWords) {
    this.addKeyWords = addKeyWords;
  }

  public SegmentRequest frame(Integer frame) {
    this.frame = frame;
    return this;
  }

   /**
   * Get frame
   * @return frame
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFrame() {
    return frame;
  }

  public void setFrame(Integer frame) {
    this.frame = frame;
  }

  public SegmentRequest length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public SegmentRequest sceneName(String sceneName) {
    this.sceneName = sceneName;
    return this;
  }

   /**
   * Get sceneName
   * @return sceneName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSceneName() {
    return sceneName;
  }

  public void setSceneName(String sceneName) {
    this.sceneName = sceneName;
  }

  public SegmentRequest tenantId(Long tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTenantId() {
    return tenantId;
  }

  public void setTenantId(Long tenantId) {
    this.tenantId = tenantId;
  }

  public SegmentRequest textContent(String textContent) {
    this.textContent = textContent;
    return this;
  }

   /**
   * Get textContent
   * @return textContent
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTextContent() {
    return textContent;
  }

  public void setTextContent(String textContent) {
    this.textContent = textContent;
  }

  public SegmentRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SegmentRequest uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentRequest segmentRequest = (SegmentRequest) o;
    return Objects.equals(this.addKeyWords, segmentRequest.addKeyWords) &&
        Objects.equals(this.frame, segmentRequest.frame) &&
        Objects.equals(this.length, segmentRequest.length) &&
        Objects.equals(this.sceneName, segmentRequest.sceneName) &&
        Objects.equals(this.tenantId, segmentRequest.tenantId) &&
        Objects.equals(this.textContent, segmentRequest.textContent) &&
        Objects.equals(this.title, segmentRequest.title) &&
        Objects.equals(this.uuid, segmentRequest.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addKeyWords, frame, length, sceneName, tenantId, textContent, title, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentRequest {\n");
    
    sb.append("    addKeyWords: ").append(toIndentedString(addKeyWords)).append("\n");
    sb.append("    frame: ").append(toIndentedString(frame)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    sceneName: ").append(toIndentedString(sceneName)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    textContent: ").append(toIndentedString(textContent)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

