/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.StudyPlanResourceResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * StudyPlanDateWiseResource
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class StudyPlanDateWiseResource   {
  @SerializedName("day")
  private String day = null;

  @SerializedName("headerMessage")
  private String headerMessage = null;

  @SerializedName("planDateNumber")
  private String planDateNumber = null;

  @SerializedName("resourceResponse")
  private List<StudyPlanResourceResponse> resourceResponse = new ArrayList<StudyPlanResourceResponse>();

  public StudyPlanDateWiseResource day(String day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDay() {
    return day;
  }

  public void setDay(String day) {
    this.day = day;
  }

  public StudyPlanDateWiseResource headerMessage(String headerMessage) {
    this.headerMessage = headerMessage;
    return this;
  }

   /**
   * Get headerMessage
   * @return headerMessage
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHeaderMessage() {
    return headerMessage;
  }

  public void setHeaderMessage(String headerMessage) {
    this.headerMessage = headerMessage;
  }

  public StudyPlanDateWiseResource planDateNumber(String planDateNumber) {
    this.planDateNumber = planDateNumber;
    return this;
  }

   /**
   * Get planDateNumber
   * @return planDateNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlanDateNumber() {
    return planDateNumber;
  }

  public void setPlanDateNumber(String planDateNumber) {
    this.planDateNumber = planDateNumber;
  }

  public StudyPlanDateWiseResource resourceResponse(List<StudyPlanResourceResponse> resourceResponse) {
    this.resourceResponse = resourceResponse;
    return this;
  }

  public StudyPlanDateWiseResource addResourceResponseItem(StudyPlanResourceResponse resourceResponseItem) {
    this.resourceResponse.add(resourceResponseItem);
    return this;
  }

   /**
   * Get resourceResponse
   * @return resourceResponse
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<StudyPlanResourceResponse> getResourceResponse() {
    return resourceResponse;
  }

  public void setResourceResponse(List<StudyPlanResourceResponse> resourceResponse) {
    this.resourceResponse = resourceResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudyPlanDateWiseResource studyPlanDateWiseResource = (StudyPlanDateWiseResource) o;
    return Objects.equals(this.day, studyPlanDateWiseResource.day) &&
        Objects.equals(this.headerMessage, studyPlanDateWiseResource.headerMessage) &&
        Objects.equals(this.planDateNumber, studyPlanDateWiseResource.planDateNumber) &&
        Objects.equals(this.resourceResponse, studyPlanDateWiseResource.resourceResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(day, headerMessage, planDateNumber, resourceResponse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudyPlanDateWiseResource {\n");
    
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    headerMessage: ").append(toIndentedString(headerMessage)).append("\n");
    sb.append("    planDateNumber: ").append(toIndentedString(planDateNumber)).append("\n");
    sb.append("    resourceResponse: ").append(toIndentedString(resourceResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

