/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.SyllabusNodeNameResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * SyllabusNodeResponseV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class SyllabusNodeResponseV2   {
  @SerializedName("beginerDays")
  private Long beginerDays = null;

  @SerializedName("beginerSpUUId")
  private String beginerSpUUId = null;

  @SerializedName("copyOfId")
  private Long copyOfId = null;

  @SerializedName("customNode")
  private Boolean customNode = null;

  @SerializedName("expertDays")
  private Long expertDays = null;

  @SerializedName("expertSpUUId")
  private String expertSpUUId = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("intermediateDays")
  private Long intermediateDays = null;

  @SerializedName("intermediateSpUUId")
  private String intermediateSpUUId = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("syllabusNodeNames")
  private List<SyllabusNodeNameResponse> syllabusNodeNames = new ArrayList<SyllabusNodeNameResponse>();

  @SerializedName("thumbnailUrl")
  private String thumbnailUrl = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("visibleInClient")
  private Boolean visibleInClient = null;

  public SyllabusNodeResponseV2 beginerDays(Long beginerDays) {
    this.beginerDays = beginerDays;
    return this;
  }

   /**
   * Get beginerDays
   * @return beginerDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBeginerDays() {
    return beginerDays;
  }

  public void setBeginerDays(Long beginerDays) {
    this.beginerDays = beginerDays;
  }

  public SyllabusNodeResponseV2 beginerSpUUId(String beginerSpUUId) {
    this.beginerSpUUId = beginerSpUUId;
    return this;
  }

   /**
   * Get beginerSpUUId
   * @return beginerSpUUId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBeginerSpUUId() {
    return beginerSpUUId;
  }

  public void setBeginerSpUUId(String beginerSpUUId) {
    this.beginerSpUUId = beginerSpUUId;
  }

  public SyllabusNodeResponseV2 copyOfId(Long copyOfId) {
    this.copyOfId = copyOfId;
    return this;
  }

   /**
   * Get copyOfId
   * @return copyOfId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCopyOfId() {
    return copyOfId;
  }

  public void setCopyOfId(Long copyOfId) {
    this.copyOfId = copyOfId;
  }

  public SyllabusNodeResponseV2 customNode(Boolean customNode) {
    this.customNode = customNode;
    return this;
  }

   /**
   * Get customNode
   * @return customNode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomNode() {
    return customNode;
  }

  public void setCustomNode(Boolean customNode) {
    this.customNode = customNode;
  }

  public SyllabusNodeResponseV2 expertDays(Long expertDays) {
    this.expertDays = expertDays;
    return this;
  }

   /**
   * Get expertDays
   * @return expertDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getExpertDays() {
    return expertDays;
  }

  public void setExpertDays(Long expertDays) {
    this.expertDays = expertDays;
  }

  public SyllabusNodeResponseV2 expertSpUUId(String expertSpUUId) {
    this.expertSpUUId = expertSpUUId;
    return this;
  }

   /**
   * Get expertSpUUId
   * @return expertSpUUId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExpertSpUUId() {
    return expertSpUUId;
  }

  public void setExpertSpUUId(String expertSpUUId) {
    this.expertSpUUId = expertSpUUId;
  }

  public SyllabusNodeResponseV2 id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SyllabusNodeResponseV2 intermediateDays(Long intermediateDays) {
    this.intermediateDays = intermediateDays;
    return this;
  }

   /**
   * Get intermediateDays
   * @return intermediateDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getIntermediateDays() {
    return intermediateDays;
  }

  public void setIntermediateDays(Long intermediateDays) {
    this.intermediateDays = intermediateDays;
  }

  public SyllabusNodeResponseV2 intermediateSpUUId(String intermediateSpUUId) {
    this.intermediateSpUUId = intermediateSpUUId;
    return this;
  }

   /**
   * Get intermediateSpUUId
   * @return intermediateSpUUId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIntermediateSpUUId() {
    return intermediateSpUUId;
  }

  public void setIntermediateSpUUId(String intermediateSpUUId) {
    this.intermediateSpUUId = intermediateSpUUId;
  }

  public SyllabusNodeResponseV2 label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public SyllabusNodeResponseV2 syllabusNodeNames(List<SyllabusNodeNameResponse> syllabusNodeNames) {
    this.syllabusNodeNames = syllabusNodeNames;
    return this;
  }

  public SyllabusNodeResponseV2 addSyllabusNodeNamesItem(SyllabusNodeNameResponse syllabusNodeNamesItem) {
    this.syllabusNodeNames.add(syllabusNodeNamesItem);
    return this;
  }

   /**
   * Get syllabusNodeNames
   * @return syllabusNodeNames
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<SyllabusNodeNameResponse> getSyllabusNodeNames() {
    return syllabusNodeNames;
  }

  public void setSyllabusNodeNames(List<SyllabusNodeNameResponse> syllabusNodeNames) {
    this.syllabusNodeNames = syllabusNodeNames;
  }

  public SyllabusNodeResponseV2 thumbnailUrl(String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
    return this;
  }

   /**
   * Get thumbnailUrl
   * @return thumbnailUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getThumbnailUrl() {
    return thumbnailUrl;
  }

  public void setThumbnailUrl(String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
  }

  public SyllabusNodeResponseV2 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SyllabusNodeResponseV2 visibleInClient(Boolean visibleInClient) {
    this.visibleInClient = visibleInClient;
    return this;
  }

   /**
   * Get visibleInClient
   * @return visibleInClient
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getVisibleInClient() {
    return visibleInClient;
  }

  public void setVisibleInClient(Boolean visibleInClient) {
    this.visibleInClient = visibleInClient;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyllabusNodeResponseV2 syllabusNodeResponseV2 = (SyllabusNodeResponseV2) o;
    return Objects.equals(this.beginerDays, syllabusNodeResponseV2.beginerDays) &&
        Objects.equals(this.beginerSpUUId, syllabusNodeResponseV2.beginerSpUUId) &&
        Objects.equals(this.copyOfId, syllabusNodeResponseV2.copyOfId) &&
        Objects.equals(this.customNode, syllabusNodeResponseV2.customNode) &&
        Objects.equals(this.expertDays, syllabusNodeResponseV2.expertDays) &&
        Objects.equals(this.expertSpUUId, syllabusNodeResponseV2.expertSpUUId) &&
        Objects.equals(this.id, syllabusNodeResponseV2.id) &&
        Objects.equals(this.intermediateDays, syllabusNodeResponseV2.intermediateDays) &&
        Objects.equals(this.intermediateSpUUId, syllabusNodeResponseV2.intermediateSpUUId) &&
        Objects.equals(this.label, syllabusNodeResponseV2.label) &&
        Objects.equals(this.syllabusNodeNames, syllabusNodeResponseV2.syllabusNodeNames) &&
        Objects.equals(this.thumbnailUrl, syllabusNodeResponseV2.thumbnailUrl) &&
        Objects.equals(this.type, syllabusNodeResponseV2.type) &&
        Objects.equals(this.visibleInClient, syllabusNodeResponseV2.visibleInClient);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beginerDays, beginerSpUUId, copyOfId, customNode, expertDays, expertSpUUId, id, intermediateDays, intermediateSpUUId, label, syllabusNodeNames, thumbnailUrl, type, visibleInClient);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyllabusNodeResponseV2 {\n");
    
    sb.append("    beginerDays: ").append(toIndentedString(beginerDays)).append("\n");
    sb.append("    beginerSpUUId: ").append(toIndentedString(beginerSpUUId)).append("\n");
    sb.append("    copyOfId: ").append(toIndentedString(copyOfId)).append("\n");
    sb.append("    customNode: ").append(toIndentedString(customNode)).append("\n");
    sb.append("    expertDays: ").append(toIndentedString(expertDays)).append("\n");
    sb.append("    expertSpUUId: ").append(toIndentedString(expertSpUUId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    intermediateDays: ").append(toIndentedString(intermediateDays)).append("\n");
    sb.append("    intermediateSpUUId: ").append(toIndentedString(intermediateSpUUId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    syllabusNodeNames: ").append(toIndentedString(syllabusNodeNames)).append("\n");
    sb.append("    thumbnailUrl: ").append(toIndentedString(thumbnailUrl)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    visibleInClient: ").append(toIndentedString(visibleInClient)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

