/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.swagger.nextsws.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.swagger.nextsws.model.ResourceResponse;
import com.nexteducation.swagger.nextsws.model.ResourceShortResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * UserResourceResponseV3
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T17:16:40.307+05:30")
public class UserResourceResponseV3   {
  @SerializedName("completeResource")
  private ResourceResponse completeResource = null;

  @SerializedName("customNode")
  private Boolean customNode = null;

  @SerializedName("customResource")
  private Boolean customResource = null;

  /**
   * Gets or Sets location
   */
  public enum LocationEnum {
    @SerializedName("Classroom")
    CLASSROOM("Classroom"),
    
    @SerializedName("Lab")
    LAB("Lab"),
    
    @SerializedName("Homework")
    HOMEWORK("Homework");

    private String value;

    LocationEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("location")
  private LocationEnum location = null;

  @SerializedName("nodeResourceId")
  private Long nodeResourceId = null;

  @SerializedName("resource")
  private ResourceShortResponse resource = null;

  @SerializedName("resourceType")
  private Long resourceType = null;

  /**
   * Gets or Sets sectionType
   */
  public enum SectionTypeEnum {
    @SerializedName("Explanation")
    EXPLANATION("Explanation"),
    
    @SerializedName("Simulation")
    SIMULATION("Simulation"),
    
    @SerializedName("Solved_Problems")
    SOLVED_PROBLEMS("Solved_Problems"),
    
    @SerializedName("Flash_Card")
    FLASH_CARD("Flash_Card"),
    
    @SerializedName("Exercise")
    EXERCISE("Exercise"),
    
    @SerializedName("TSP")
    TSP("TSP"),
    
    @SerializedName("Library")
    LIBRARY("Library"),
    
    @SerializedName("CYU")
    CYU("CYU"),
    
    @SerializedName("Formative_Assessments")
    FORMATIVE_ASSESSMENTS("Formative_Assessments"),
    
    @SerializedName("Summative_Assessments")
    SUMMATIVE_ASSESSMENTS("Summative_Assessments"),
    
    @SerializedName("HOTS")
    HOTS("HOTS"),
    
    @SerializedName("Quiz")
    QUIZ("Quiz"),
    
    @SerializedName("Lesson_Plan")
    LESSON_PLAN("Lesson_Plan"),
    
    @SerializedName("Paper_Cutting")
    PAPER_CUTTING("Paper_Cutting"),
    
    @SerializedName("Hands_On_Activity")
    HANDS_ON_ACTIVITY("Hands_On_Activity"),
    
    @SerializedName("Practical_Geometry")
    PRACTICAL_GEOMETRY("Practical_Geometry"),
    
    @SerializedName("Activity")
    ACTIVITY("Activity"),
    
    @SerializedName("Experiment")
    EXPERIMENT("Experiment"),
    
    @SerializedName("Story")
    STORY("Story"),
    
    @SerializedName("QuestAns")
    QUESTANS("QuestAns"),
    
    @SerializedName("Wiki")
    WIKI("Wiki"),
    
    @SerializedName("MindMap")
    MINDMAP("MindMap"),
    
    @SerializedName("TSP_VIDEO")
    TSP_VIDEO("TSP_VIDEO"),
    
    @SerializedName("Textbook_Activity")
    TEXTBOOK_ACTIVITY("Textbook_Activity"),
    
    @SerializedName("Companion_Activity")
    COMPANION_ACTIVITY("Companion_Activity"),
    
    @SerializedName("Teacher_Manual_Activity")
    TEACHER_MANUAL_ACTIVITY("Teacher_Manual_Activity"),
    
    @SerializedName("PPVideo")
    PPVIDEO("PPVideo"),
    
    @SerializedName("ASL")
    ASL("ASL"),
    
    @SerializedName("CBT")
    CBT("CBT"),
    
    @SerializedName("Test_Paper")
    TEST_PAPER("Test_Paper"),
    
    @SerializedName("EBooks")
    EBOOKS("EBooks"),
    
    @SerializedName("Other")
    OTHER("Other"),
    
    @SerializedName("NoteBook")
    NOTEBOOK("NoteBook"),
    
    @SerializedName("Assessment")
    ASSESSMENT("Assessment"),
    
    @SerializedName("Post")
    POST("Post"),
    
    @SerializedName("Question")
    QUESTION("Question"),
    
    @SerializedName("WhiteBoard")
    WHITEBOARD("WhiteBoard");

    private String value;

    SectionTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("sectionType")
  private SectionTypeEnum sectionType = null;

  @SerializedName("syllabusId")
  private Long syllabusId = null;

  @SerializedName("syllanusNodeId")
  private Long syllanusNodeId = null;

  public UserResourceResponseV3 completeResource(ResourceResponse completeResource) {
    this.completeResource = completeResource;
    return this;
  }

   /**
   * Get completeResource
   * @return completeResource
  **/
  @ApiModelProperty(example = "null", value = "")
  public ResourceResponse getCompleteResource() {
    return completeResource;
  }

  public void setCompleteResource(ResourceResponse completeResource) {
    this.completeResource = completeResource;
  }

  public UserResourceResponseV3 customNode(Boolean customNode) {
    this.customNode = customNode;
    return this;
  }

   /**
   * Get customNode
   * @return customNode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomNode() {
    return customNode;
  }

  public void setCustomNode(Boolean customNode) {
    this.customNode = customNode;
  }

  public UserResourceResponseV3 customResource(Boolean customResource) {
    this.customResource = customResource;
    return this;
  }

   /**
   * Get customResource
   * @return customResource
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomResource() {
    return customResource;
  }

  public void setCustomResource(Boolean customResource) {
    this.customResource = customResource;
  }

  public UserResourceResponseV3 location(LocationEnum location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocationEnum getLocation() {
    return location;
  }

  public void setLocation(LocationEnum location) {
    this.location = location;
  }

  public UserResourceResponseV3 nodeResourceId(Long nodeResourceId) {
    this.nodeResourceId = nodeResourceId;
    return this;
  }

   /**
   * Get nodeResourceId
   * @return nodeResourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNodeResourceId() {
    return nodeResourceId;
  }

  public void setNodeResourceId(Long nodeResourceId) {
    this.nodeResourceId = nodeResourceId;
  }

  public UserResourceResponseV3 resource(ResourceShortResponse resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  @ApiModelProperty(example = "null", value = "")
  public ResourceShortResponse getResource() {
    return resource;
  }

  public void setResource(ResourceShortResponse resource) {
    this.resource = resource;
  }

  public UserResourceResponseV3 resourceType(Long resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getResourceType() {
    return resourceType;
  }

  public void setResourceType(Long resourceType) {
    this.resourceType = resourceType;
  }

  public UserResourceResponseV3 sectionType(SectionTypeEnum sectionType) {
    this.sectionType = sectionType;
    return this;
  }

   /**
   * Get sectionType
   * @return sectionType
  **/
  @ApiModelProperty(example = "null", value = "")
  public SectionTypeEnum getSectionType() {
    return sectionType;
  }

  public void setSectionType(SectionTypeEnum sectionType) {
    this.sectionType = sectionType;
  }

  public UserResourceResponseV3 syllabusId(Long syllabusId) {
    this.syllabusId = syllabusId;
    return this;
  }

   /**
   * Get syllabusId
   * @return syllabusId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSyllabusId() {
    return syllabusId;
  }

  public void setSyllabusId(Long syllabusId) {
    this.syllabusId = syllabusId;
  }

  public UserResourceResponseV3 syllanusNodeId(Long syllanusNodeId) {
    this.syllanusNodeId = syllanusNodeId;
    return this;
  }

   /**
   * Get syllanusNodeId
   * @return syllanusNodeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSyllanusNodeId() {
    return syllanusNodeId;
  }

  public void setSyllanusNodeId(Long syllanusNodeId) {
    this.syllanusNodeId = syllanusNodeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserResourceResponseV3 userResourceResponseV3 = (UserResourceResponseV3) o;
    return Objects.equals(this.completeResource, userResourceResponseV3.completeResource) &&
        Objects.equals(this.customNode, userResourceResponseV3.customNode) &&
        Objects.equals(this.customResource, userResourceResponseV3.customResource) &&
        Objects.equals(this.location, userResourceResponseV3.location) &&
        Objects.equals(this.nodeResourceId, userResourceResponseV3.nodeResourceId) &&
        Objects.equals(this.resource, userResourceResponseV3.resource) &&
        Objects.equals(this.resourceType, userResourceResponseV3.resourceType) &&
        Objects.equals(this.sectionType, userResourceResponseV3.sectionType) &&
        Objects.equals(this.syllabusId, userResourceResponseV3.syllabusId) &&
        Objects.equals(this.syllanusNodeId, userResourceResponseV3.syllanusNodeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completeResource, customNode, customResource, location, nodeResourceId, resource, resourceType, sectionType, syllabusId, syllanusNodeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserResourceResponseV3 {\n");
    
    sb.append("    completeResource: ").append(toIndentedString(completeResource)).append("\n");
    sb.append("    customNode: ").append(toIndentedString(customNode)).append("\n");
    sb.append("    customResource: ").append(toIndentedString(customResource)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    nodeResourceId: ").append(toIndentedString(nodeResourceId)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    sectionType: ").append(toIndentedString(sectionType)).append("\n");
    sb.append("    syllabusId: ").append(toIndentedString(syllabusId)).append("\n");
    sb.append("    syllanusNodeId: ").append(toIndentedString(syllanusNodeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

